
# This file controls the configuration for Supabase CLI
project_id = "qlhovvqcwjdbirmekdoy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[functions]
[functions.send-newsletter]
verify_jwt = false

[functions.setup-newsletter-cron]
verify_jwt = false
