
project_id = "qlhovvqcwjdbirmekdoy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.oauth-exchange]
verify_jwt = false

[functions.cloud-storage]
verify_jwt = true
