project_id = "qlhovvqcwjdbirmekdoy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.luvvix-translate-api]
verify_jwt = false

[functions.luvvix-weather-api]
verify_jwt = false

[functions.luvvix-forms-api]
verify_jwt = false

[functions.koofr-oauth]
verify_jwt = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
