
import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

// Types pour les langues supportées
export type Language = 'fr' | 'en' | 'es' | 'pt' | 'de' | 'zh' | 'ru' | 'it' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Dictionnaire complet des traductions
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation et général
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.news': 'Actualités',
    'nav.translate': 'Traduction',
    'nav.mindmap': 'Carte mentale',
    'nav.weather': 'Météo',
    'nav.explore': 'Explorer',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',
    'nav.settings': 'Paramètres',
    'nav.profile': 'Profil',
    
    // Page d'accueil
    'hero.title': 'Bienvenue sur LuvviX',
    'hero.subtitle': 'La plateforme tout-en-un pour vos besoins numériques',
    'hero.description': 'Découvrez notre écosystème d\'applications innovantes conçues pour améliorer votre productivité et votre créativité.',
    'hero.cta': 'Commencer',
    'hero.learn_more': 'En savoir plus',
    
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.welcome': 'Bienvenue',
    'dashboard.stats': 'Statistiques',
    'dashboard.recent': 'Activités récentes',
    'dashboard.apps': 'Applications',
    'dashboard.quick_actions': 'Actions rapides',
    'dashboard.settings': 'Paramètres',
    'dashboard.language': 'Langue',
    'dashboard.theme': 'Thème',
    'dashboard.notifications': 'Notifications',
    'dashboard.privacy': 'Confidentialité',
    'dashboard.account': 'Compte',
    'dashboard.security': 'Sécurité',
    'dashboard.help': 'Aide',
    'dashboard.about': 'À propos',
    
    // Actualités
    'news.title': 'Actualités',
    'news.subtitle': 'Restez informé',
    'news.description': 'Découvrez les dernières actualités du monde entier avec notre système de curation intelligent.',
    'news.latest': 'Dernières actualités',
    'news.search': 'Rechercher des actualités...',
    'news.loading': 'Chargement...',
    'news.error': 'Erreur lors du chargement',
    'news.categories.all': 'Toutes',
    'news.categories.technology': 'Technologie',
    'news.categories.business': 'Business',
    'news.categories.sports': 'Sports',
    'news.categories.entertainment': 'Divertissement',
    'news.categories.health': 'Santé',
    'news.categories.science': 'Science',
    
    // Traduction
    'translate.title': 'Traduction IA',
    'translate.subtitle': 'Traduction intelligente',
    'translate.description': 'Traduisez instantanément du texte dans plus de 100 langues avec notre IA avancée.',
    'translate.input_placeholder': 'Entrez votre texte à traduire...',
    'translate.output_placeholder': 'La traduction apparaîtra ici...',
    'translate.from': 'Depuis',
    'translate.to': 'Vers',
    'translate.auto_detect': 'Détection automatique',
    'translate.translate_btn': 'Traduire',
    'translate.copy': 'Copier',
    'translate.clear': 'Effacer',
    
    // Carte mentale
    'mindmap.title': 'Carte mentale IA',
    'mindmap.subtitle': 'Visualisez vos idées',
    'mindmap.description': 'Créez des cartes mentales interactives avec l\'aide de notre IA pour organiser vos pensées.',
    'mindmap.input_placeholder': 'Décrivez votre sujet ou idée...',
    'mindmap.generate': 'Générer la carte',
    'mindmap.loading': 'Génération en cours...',
    
    // Météo
    'weather.title': 'Météo',
    'weather.current': 'Météo actuelle',
    'weather.description': 'Consultez les conditions météorologiques actuelles et les prévisions.',
    'weather.location': 'Localisation',
    'weather.temperature': 'Température',
    'weather.humidity': 'Humidité',
    'weather.wind': 'Vent',
    'weather.pressure': 'Pression',
    
    // LuvviX Explore
    'explore.title': 'LuvviX Explore',
    'explore.subtitle': 'Recherche IA multimodale',
    'explore.description': 'Explorez le web, analysez des fichiers et obtenez des réponses intelligentes avec notre IA avancée.',
    'explore.search_placeholder': 'Recherchez n\'importe quoi...',
    'explore.search_btn': 'Rechercher',
    'explore.upload_file': 'Télécharger un fichier',
    'explore.recent_searches': 'Recherches récentes',
    'explore.suggested_searches': 'Recherches suggérées',
    'explore.search_web': 'Recherche web',
    'explore.search_videos': 'Recherche vidéos',
    'explore.search_images': 'Recherche images',
    'explore.search_files': 'Recherche fichiers',
    'explore.ai_summary': 'Résumé IA',
    'explore.ask_question': 'Poser une question',
    'explore.share_result': 'Partager le résultat',
    'explore.create_mindmap': 'Créer une carte mentale',
    'explore.translate_result': 'Traduire le résultat',
    'explore.create_form': 'Créer un formulaire',
    'explore.create_agent': 'Créer un agent IA',
    'explore.publish_center': 'Publier sur Center',
    'explore.results_found': 'résultats trouvés',
    'explore.no_results': 'Aucun résultat trouvé',
    'explore.loading': 'Recherche en cours...',
    'explore.categories.web': 'Web',
    'explore.categories.videos': 'Vidéos',
    'explore.categories.images': 'Images',
    'explore.categories.files': 'Fichiers',
    'explore.categories.discussions': 'Discussions',
    
    // Authentification
    'auth.login': 'Se connecter',
    'auth.signup': 'S\'inscrire',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirm_password': 'Confirmer le mot de passe',
    'auth.forgot_password': 'Mot de passe oublié ?',
    'auth.no_account': 'Pas de compte ?',
    'auth.have_account': 'Déjà un compte ?',
    'auth.login_success': 'Connexion réussie',
    'auth.signup_success': 'Inscription réussie',
    'auth.error': 'Erreur d\'authentification',
    
    // Footer
    'footer.about': 'À propos',
    'footer.contact': 'Contact',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',
    'footer.language': 'Langue',
    'footer.rights': 'Tous droits réservés',
    
    // Messages communs
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur est survenue',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.share': 'Partager',
    'common.copy': 'Copier',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.upload': 'Télécharger',
    'common.download': 'Télécharger',
    'common.refresh': 'Actualiser',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.close': 'Fermer',
    'common.open': 'Ouvrir',
    'common.show_more': 'Voir plus',
    'common.show_less': 'Voir moins',
  },
  en: {
    // Navigation and general
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.news': 'News',
    'nav.translate': 'Translate',
    'nav.mindmap': 'Mind Map',
    'nav.weather': 'Weather',
    'nav.explore': 'Explore',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    
    // Homepage
    'hero.title': 'Welcome to LuvviX',
    'hero.subtitle': 'The all-in-one platform for your digital needs',
    'hero.description': 'Discover our ecosystem of innovative applications designed to enhance your productivity and creativity.',
    'hero.cta': 'Get Started',
    'hero.learn_more': 'Learn More',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.stats': 'Statistics',
    'dashboard.recent': 'Recent Activities',
    'dashboard.apps': 'Applications',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.settings': 'Settings',
    'dashboard.language': 'Language',
    'dashboard.theme': 'Theme',
    'dashboard.notifications': 'Notifications',
    'dashboard.privacy': 'Privacy',
    'dashboard.account': 'Account',
    'dashboard.security': 'Security',
    'dashboard.help': 'Help',
    'dashboard.about': 'About',
    
    // News
    'news.title': 'News',
    'news.subtitle': 'Stay Informed',
    'news.description': 'Discover the latest news from around the world with our intelligent curation system.',
    'news.latest': 'Latest News',
    'news.search': 'Search news...',
    'news.loading': 'Loading...',
    'news.error': 'Error loading',
    'news.categories.all': 'All',
    'news.categories.technology': 'Technology',
    'news.categories.business': 'Business',
    'news.categories.sports': 'Sports',
    'news.categories.entertainment': 'Entertainment',
    'news.categories.health': 'Health',
    'news.categories.science': 'Science',
    
    // Translation
    'translate.title': 'AI Translation',
    'translate.subtitle': 'Smart Translation',
    'translate.description': 'Instantly translate text in over 100 languages with our advanced AI.',
    'translate.input_placeholder': 'Enter your text to translate...',
    'translate.output_placeholder': 'Translation will appear here...',
    'translate.from': 'From',
    'translate.to': 'To',
    'translate.auto_detect': 'Auto-detect',
    'translate.translate_btn': 'Translate',
    'translate.copy': 'Copy',
    'translate.clear': 'Clear',
    
    // Mind map
    'mindmap.title': 'AI Mind Map',
    'mindmap.subtitle': 'Visualize Your Ideas',
    'mindmap.description': 'Create interactive mind maps with the help of our AI to organize your thoughts.',
    'mindmap.input_placeholder': 'Describe your topic or idea...',
    'mindmap.generate': 'Generate Map',
    'mindmap.loading': 'Generating...',
    
    // Weather
    'weather.title': 'Weather',
    'weather.current': 'Current Weather',
    'weather.description': 'Check current weather conditions and forecasts.',
    'weather.location': 'Location',
    'weather.temperature': 'Temperature',
    'weather.humidity': 'Humidity',
    'weather.wind': 'Wind',
    'weather.pressure': 'Pressure',
    
    // LuvviX Explore
    'explore.title': 'LuvviX Explore',
    'explore.subtitle': 'Multimodal AI Search',
    'explore.description': 'Explore the web, analyze files, and get intelligent answers with our advanced AI.',
    'explore.search_placeholder': 'Search anything...',
    'explore.search_btn': 'Search',
    'explore.upload_file': 'Upload File',
    'explore.recent_searches': 'Recent Searches',
    'explore.suggested_searches': 'Suggested Searches',
    'explore.search_web': 'Web Search',
    'explore.search_videos': 'Video Search',
    'explore.search_images': 'Image Search',
    'explore.search_files': 'File Search',
    'explore.ai_summary': 'AI Summary',
    'explore.ask_question': 'Ask a Question',
    'explore.share_result': 'Share Result',
    'explore.create_mindmap': 'Create Mind Map',
    'explore.translate_result': 'Translate Result',
    'explore.create_form': 'Create Form',
    'explore.create_agent': 'Create AI Agent',
    'explore.publish_center': 'Publish to Center',
    'explore.results_found': 'results found',
    'explore.no_results': 'No results found',
    'explore.loading': 'Searching...',
    'explore.categories.web': 'Web',
    'explore.categories.videos': 'Videos',
    'explore.categories.images': 'Images',
    'explore.categories.files': 'Files',
    'explore.categories.discussions': 'Discussions',
    
    // Authentication
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.forgot_password': 'Forgot Password?',
    'auth.no_account': 'No account?',
    'auth.have_account': 'Already have an account?',
    'auth.login_success': 'Login successful',
    'auth.signup_success': 'Signup successful',
    'auth.error': 'Authentication error',
    
    // Footer
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.language': 'Language',
    'footer.rights': 'All rights reserved',
    
    // Common messages
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.refresh': 'Refresh',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.show_more': 'Show More',
    'common.show_less': 'Show Less',
  },
  es: {
    // Navegación y general
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel',
    'nav.news': 'Noticias',
    'nav.translate': 'Traducir',
    'nav.mindmap': 'Mapa Mental',
    'nav.weather': 'Clima',
    'nav.explore': 'Explorar',
    'nav.login': 'Iniciar Sesión',
    'nav.logout': 'Cerrar Sesión',
    'nav.settings': 'Configuración',
    'nav.profile': 'Perfil',
    
    // Página principal
    'hero.title': 'Bienvenido a LuvviX',
    'hero.subtitle': 'La plataforma todo en uno para tus necesidades digitales',
    'hero.description': 'Descubre nuestro ecosistema de aplicaciones innovadoras diseñadas para mejorar tu productividad y creatividad.',
    'hero.cta': 'Comenzar',
    'hero.learn_more': 'Saber Más',
    
    // Panel
    'dashboard.title': 'Panel',
    'dashboard.welcome': 'Bienvenido',
    'dashboard.stats': 'Estadísticas',
    'dashboard.recent': 'Actividades Recientes',
    'dashboard.apps': 'Aplicaciones',
    'dashboard.quick_actions': 'Acciones Rápidas',
    'dashboard.settings': 'Configuración',
    'dashboard.language': 'Idioma',
    'dashboard.theme': 'Tema',
    'dashboard.notifications': 'Notificaciones',
    'dashboard.privacy': 'Privacidad',
    'dashboard.account': 'Cuenta',
    'dashboard.security': 'Seguridad',
    'dashboard.help': 'Ayuda',
    'dashboard.about': 'Acerca de',
    
    // Noticias
    'news.title': 'Noticias',
    'news.subtitle': 'Mantente Informado',
    'news.description': 'Descubre las últimas noticias de todo el mundo con nuestro sistema de curación inteligente.',
    'news.latest': 'Últimas Noticias',
    'news.search': 'Buscar noticias...',
    'news.loading': 'Cargando...',
    'news.error': 'Error al cargar',
    'news.categories.all': 'Todas',
    'news.categories.technology': 'Tecnología',
    'news.categories.business': 'Negocios',
    'news.categories.sports': 'Deportes',
    'news.categories.entertainment': 'Entretenimiento',
    'news.categories.health': 'Salud',
    'news.categories.science': 'Ciencia',
    
    // Traducción
    'translate.title': 'Traducción IA',
    'translate.subtitle': 'Traducción Inteligente',
    'translate.description': 'Traduce instantáneamente texto en más de 100 idiomas con nuestra IA avanzada.',
    'translate.input_placeholder': 'Ingresa tu texto para traducir...',
    'translate.output_placeholder': 'La traducción aparecerá aquí...',
    'translate.from': 'Desde',
    'translate.to': 'Hacia',
    'translate.auto_detect': 'Detección automática',
    'translate.translate_btn': 'Traducir',
    'translate.copy': 'Copiar',
    'translate.clear': 'Limpiar',
    
    // Mapa mental
    'mindmap.title': 'Mapa Mental IA',
    'mindmap.subtitle': 'Visualiza Tus Ideas',
    'mindmap.description': 'Crea mapas mentales interactivos con la ayuda de nuestra IA para organizar tus pensamientos.',
    'mindmap.input_placeholder': 'Describe tu tema o idea...',
    'mindmap.generate': 'Generar Mapa',
    'mindmap.loading': 'Generando...',
    
    // Clima
    'weather.title': 'Clima',
    'weather.current': 'Clima Actual',
    'weather.description': 'Consulta las condiciones climáticas actuales y pronósticos.',
    'weather.location': 'Ubicación',
    'weather.temperature': 'Temperatura',
    'weather.humidity': 'Humedad',
    'weather.wind': 'Viento',
    'weather.pressure': 'Presión',
    
    // LuvviX Explore
    'explore.title': 'LuvviX Explore',
    'explore.subtitle': 'Búsqueda IA Multimodal',
    'explore.description': 'Explora la web, analiza archivos y obtén respuestas inteligentes con nuestra IA avanzada.',
    'explore.search_placeholder': 'Busca cualquier cosa...',
    'explore.search_btn': 'Buscar',
    'explore.upload_file': 'Subir Archivo',
    'explore.recent_searches': 'Búsquedas Recientes',
    'explore.suggested_searches': 'Búsquedas Sugeridas',
    'explore.search_web': 'Búsqueda Web',
    'explore.search_videos': 'Búsqueda de Videos',
    'explore.search_images': 'Búsqueda de Imágenes',
    'explore.search_files': 'Búsqueda de Archivos',
    'explore.ai_summary': 'Resumen IA',
    'explore.ask_question': 'Hacer una Pregunta',
    'explore.share_result': 'Compartir Resultado',
    'explore.create_mindmap': 'Crear Mapa Mental',
    'explore.translate_result': 'Traducir Resultado',
    'explore.create_form': 'Crear Formulario',
    'explore.create_agent': 'Crear Agente IA',
    'explore.publish_center': 'Publicar en Center',
    'explore.results_found': 'resultados encontrados',
    'explore.no_results': 'No se encontraron resultados',
    'explore.loading': 'Buscando...',
    'explore.categories.web': 'Web',
    'explore.categories.videos': 'Videos',
    'explore.categories.images': 'Imágenes',
    'explore.categories.files': 'Archivos',
    'explore.categories.discussions': 'Discusiones',
    
    // Autenticación
    'auth.login': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.confirm_password': 'Confirmar Contraseña',
    'auth.forgot_password': '¿Olvidaste tu contraseña?',
    'auth.no_account': '¿No tienes cuenta?',
    'auth.have_account': '¿Ya tienes cuenta?',
    'auth.login_success': 'Inicio de sesión exitoso',
    'auth.signup_success': 'Registro exitoso',
    'auth.error': 'Error de autenticación',
    
    // Pie de página
    'footer.about': 'Acerca de',
    'footer.contact': 'Contacto',
    'footer.privacy': 'Privacidad',
    'footer.terms': 'Términos',
    'footer.language': 'Idioma',
    'footer.rights': 'Todos los derechos reservados',
    
    // Mensajes comunes
    'common.loading': 'Cargando...',
    'common.error': 'Ocurrió un error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.share': 'Compartir',
    'common.copy': 'Copiar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.upload': 'Subir',
    'common.download': 'Descargar',
    'common.refresh': 'Actualizar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.close': 'Cerrar',
    'common.open': 'Abrir',
    'common.show_more': 'Ver Más',
    'common.show_less': 'Ver Menos',
  },
  pt: {
    // Navegação e geral
    'nav.home': 'Início',
    'nav.dashboard': 'Painel',
    'nav.news': 'Notícias',
    'nav.translate': 'Traduzir',
    'nav.mindmap': 'Mapa Mental',
    'nav.weather': 'Clima',
    'nav.explore': 'Explorar',
    'nav.login': 'Entrar',
    'nav.logout': 'Sair',
    'nav.settings': 'Configurações',
    'nav.profile': 'Perfil',
    
    // Página inicial
    'hero.title': 'Bem-vindo ao LuvviX',
    'hero.subtitle': 'A plataforma tudo-em-um para suas necessidades digitais',
    'hero.description': 'Descubra nosso ecossistema de aplicações inovadoras projetadas para melhorar sua produtividade e criatividade.',
    'hero.cta': 'Começar',
    'hero.learn_more': 'Saber Mais',
    
    // Painel
    'dashboard.title': 'Painel',
    'dashboard.welcome': 'Bem-vindo',
    'dashboard.stats': 'Estatísticas',
    'dashboard.recent': 'Atividades Recentes',
    'dashboard.apps': 'Aplicações',
    'dashboard.quick_actions': 'Ações Rápidas',
    'dashboard.settings': 'Configurações',
    'dashboard.language': 'Idioma',
    'dashboard.theme': 'Tema',
    'dashboard.notifications': 'Notificações',
    'dashboard.privacy': 'Privacidade',
    'dashboard.account': 'Conta',
    'dashboard.security': 'Segurança',
    'dashboard.help': 'Ajuda',
    'dashboard.about': 'Sobre',
    
    // Notícias
    'news.title': 'Notícias',
    'news.subtitle': 'Mantenha-se Informado',
    'news.description': 'Descubra as últimas notícias de todo o mundo com nosso sistema de curadoria inteligente.',
    'news.latest': 'Últimas Notícias',
    'news.search': 'Pesquisar notícias...',
    'news.loading': 'Carregando...',
    'news.error': 'Erro ao carregar',
    'news.categories.all': 'Todas',
    'news.categories.technology': 'Tecnologia',
    'news.categories.business': 'Negócios',
    'news.categories.sports': 'Esportes',
    'news.categories.entertainment': 'Entretenimento',
    'news.categories.health': 'Saúde',
    'news.categories.science': 'Ciência',
    
    // Tradução
    'translate.title': 'Tradução IA',
    'translate.subtitle': 'Tradução Inteligente',
    'translate.description': 'Traduza instantaneamente texto em mais de 100 idiomas com nossa IA avançada.',
    'translate.input_placeholder': 'Digite seu texto para traduzir...',
    'translate.output_placeholder': 'A tradução aparecerá aqui...',
    'translate.from': 'De',
    'translate.to': 'Para',
    'translate.auto_detect': 'Detecção automática',
    'translate.translate_btn': 'Traduzir',
    'translate.copy': 'Copiar',
    'translate.clear': 'Limpar',
    
    // Mapa mental
    'mindmap.title': 'Mapa Mental IA',
    'mindmap.subtitle': 'Visualize Suas Ideias',
    'mindmap.description': 'Crie mapas mentais interativos com a ajuda de nossa IA para organizar seus pensamentos.',
    'mindmap.input_placeholder': 'Descreva seu tópico ou ideia...',
    'mindmap.generate': 'Gerar Mapa',
    'mindmap.loading': 'Gerando...',
    
    // Clima
    'weather.title': 'Clima',
    'weather.current': 'Clima Atual',
    'weather.description': 'Consulte as condições climáticas atuais e previsões.',
    'weather.location': 'Localização',
    'weather.temperature': 'Temperatura',
    'weather.humidity': 'Umidade',
    'weather.wind': 'Vento',
    'weather.pressure': 'Pressão',
    
    // LuvviX Explore
    'explore.title': 'LuvviX Explore',
    'explore.subtitle': 'Busca IA Multimodal',
    'explore.description': 'Explore a web, analise arquivos e obtenha respostas inteligentes com nossa IA avançada.',
    'explore.search_placeholder': 'Pesquisar qualquer coisa...',
    'explore.search_btn': 'Pesquisar',
    'explore.upload_file': 'Enviar Arquivo',
    'explore.recent_searches': 'Pesquisas Recentes',
    'explore.suggested_searches': 'Pesquisas Sugeridas',
    'explore.search_web': 'Busca Web',
    'explore.search_videos': 'Busca de Vídeos',
    'explore.search_images': 'Busca de Imagens',
    'explore.search_files': 'Busca de Arquivos',
    'explore.ai_summary': 'Resumo IA',
    'explore.ask_question': 'Fazer uma Pergunta',
    'explore.share_result': 'Compartilhar Resultado',
    'explore.create_mindmap': 'Criar Mapa Mental',
    'explore.translate_result': 'Traduzir Resultado',
    'explore.create_form': 'Criar Formulário',
    'explore.create_agent': 'Criar Agente IA',
    'explore.publish_center': 'Publicar no Center',
    'explore.results_found': 'resultados encontrados',
    'explore.no_results': 'Nenhum resultado encontrado',
    'explore.loading': 'Pesquisando...',
    'explore.categories.web': 'Web',
    'explore.categories.videos': 'Vídeos',
    'explore.categories.images': 'Imagens',
    'explore.categories.files': 'Arquivos',
    'explore.categories.discussions': 'Discussões',
    
    // Autenticação
    'auth.login': 'Entrar',
    'auth.signup': 'Cadastrar',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.confirm_password': 'Confirmar Senha',
    'auth.forgot_password': 'Esqueceu a senha?',
    'auth.no_account': 'Não tem conta?',
    'auth.have_account': 'Já tem conta?',
    'auth.login_success': 'Login bem-sucedido',
    'auth.signup_success': 'Cadastro bem-sucedido',
    'auth.error': 'Erro de autenticação',
    
    // Rodapé
    'footer.about': 'Sobre',
    'footer.contact': 'Contato',
    'footer.privacy': 'Privacidade',
    'footer.terms': 'Termos',
    'footer.language': 'Idioma',
    'footer.rights': 'Todos os direitos reservados',
    
    // Mensagens comuns
    'common.loading': 'Carregando...',
    'common.error': 'Ocorreu um erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Salvar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.share': 'Compartilhar',
    'common.copy': 'Copiar',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.upload': 'Enviar',
    'common.download': 'Baixar',
    'common.refresh': 'Atualizar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.close': 'Fechar',
    'common.open': 'Abrir',
    'common.show_more': 'Ver Mais',
    'common.show_less': 'Ver Menos',
  },
  de: {
    // Navigation und allgemein
    'nav.home': 'Startseite',
    'nav.dashboard': 'Dashboard',
    'nav.news': 'Nachrichten',
    'nav.translate': 'Übersetzen',
    'nav.mindmap': 'Mind Map',
    'nav.weather': 'Wetter',
    'nav.explore': 'Erkunden',
    'nav.login': 'Anmelden',
    'nav.logout': 'Abmelden',
    'nav.settings': 'Einstellungen',
    'nav.profile': 'Profil',
    
    // Startseite
    'hero.title': 'Willkommen bei LuvviX',
    'hero.subtitle': 'Die All-in-One-Plattform für Ihre digitalen Bedürfnisse',
    'hero.description': 'Entdecken Sie unser Ökosystem innovativer Anwendungen zur Steigerung Ihrer Produktivität und Kreativität.',
    'hero.cta': 'Loslegen',
    'hero.learn_more': 'Mehr erfahren',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Willkommen',
    'dashboard.stats': 'Statistiken',
    'dashboard.recent': 'Kürzliche Aktivitäten',
    'dashboard.apps': 'Anwendungen',
    'dashboard.quick_actions': 'Schnellaktionen',
    'dashboard.settings': 'Einstellungen',
    'dashboard.language': 'Sprache',
    'dashboard.theme': 'Design',
    'dashboard.notifications': 'Benachrichtigungen',
    'dashboard.privacy': 'Datenschutz',
    'dashboard.account': 'Konto',
    'dashboard.security': 'Sicherheit',
    'dashboard.help': 'Hilfe',
    'dashboard.about': 'Über',
    
    // Nachrichten
    'news.title': 'Nachrichten',
    'news.subtitle': 'Bleiben Sie informiert',
    'news.description': 'Entdecken Sie die neuesten Nachrichten aus aller Welt mit unserem intelligenten Kuratierungssystem.',
    'news.latest': 'Neueste Nachrichten',
    'news.search': 'Nachrichten suchen...',
    'news.loading': 'Lädt...',
    'news.error': 'Fehler beim Laden',
    'news.categories.all': 'Alle',
    'news.categories.technology': 'Technologie',
    'news.categories.business': 'Wirtschaft',
    'news.categories.sports': 'Sport',
    'news.categories.entertainment': 'Unterhaltung',
    'news.categories.health': 'Gesundheit',
    'news.categories.science': 'Wissenschaft',
    
    // Übersetzung
    'translate.title': 'KI-Übersetzung',
    'translate.subtitle': 'Intelligente Übersetzung',
    'translate.description': 'Übersetzen Sie sofort Text in über 100 Sprachen mit unserer fortschrittlichen KI.',
    'translate.input_placeholder': 'Geben Sie Ihren Text zum Übersetzen ein...',
    'translate.output_placeholder': 'Die Übersetzung wird hier angezeigt...',
    'translate.from': 'Von',
    'translate.to': 'Nach',
    'translate.auto_detect': 'Automatische Erkennung',
    'translate.translate_btn': 'Übersetzen',
    'translate.copy': 'Kopieren',
    'translate.clear': 'Löschen',
    
    // Mind Map
    'mindmap.title': 'KI-Mind Map',
    'mindmap.subtitle': 'Visualisieren Sie Ihre Ideen',
    'mindmap.description': 'Erstellen Sie interaktive Mind Maps mit Hilfe unserer KI zur Organisation Ihrer Gedanken.',
    'mindmap.input_placeholder': 'Beschreiben Sie Ihr Thema oder Ihre Idee...',
    'mindmap.generate': 'Karte generieren',
    'mindmap.loading': 'Generiert...',
    
    // Wetter
    'weather.title': 'Wetter',
    'weather.current': 'Aktuelles Wetter',
    'weather.description': 'Überprüfen Sie aktuelle Wetterbedingungen und Vorhersagen.',
    'weather.location': 'Standort',
    'weather.temperature': 'Temperatur',
    'weather.humidity': 'Luftfeuchtigkeit',
    'weather.wind': 'Wind',
    'weather.pressure': 'Druck',
    
    // LuvviX Explore
    'explore.title': 'LuvviX Explore',
    'explore.subtitle': 'Multimodale KI-Suche',
    'explore.description': 'Erkunden Sie das Web, analysieren Sie Dateien und erhalten Sie intelligente Antworten mit unserer fortschrittlichen KI.',
    'explore.search_placeholder': 'Alles suchen...',
    'explore.search_btn': 'Suchen',
    'explore.upload_file': 'Datei hochladen',
    'explore.recent_searches': 'Kürzliche Suchen',
    'explore.suggested_searches': 'Vorgeschlagene Suchen',
    'explore.search_web': 'Web-Suche',
    'explore.search_videos': 'Video-Suche',
    'explore.search_images': 'Bild-Suche',
    'explore.search_files': 'Datei-Suche',
    'explore.ai_summary': 'KI-Zusammenfassung',
    'explore.ask_question': 'Frage stellen',
    'explore.share_result': 'Ergebnis teilen',
    'explore.create_mindmap': 'Mind Map erstellen',
    'explore.translate_result': 'Ergebnis übersetzen',
    'explore.create_form': 'Formular erstellen',
    'explore.create_agent': 'KI-Agent erstellen',
    'explore.publish_center': 'Im Center veröffentlichen',
    'explore.results_found': 'Ergebnisse gefunden',
    'explore.no_results': 'Keine Ergebnisse gefunden',
    'explore.loading': 'Sucht...',
    'explore.categories.web': 'Web',
    'explore.categories.videos': 'Videos',
    'explore.categories.images': 'Bilder',
    'explore.categories.files': 'Dateien',
    'explore.categories.discussions': 'Diskussionen',
    
    // Authentifizierung
    'auth.login': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirm_password': 'Passwort bestätigen',
    'auth.forgot_password': 'Passwort vergessen?',
    'auth.no_account': 'Kein Konto?',
    'auth.have_account': 'Bereits ein Konto?',
    'auth.login_success': 'Anmeldung erfolgreich',
    'auth.signup_success': 'Registrierung erfolgreich',
    'auth.error': 'Authentifizierungsfehler',
    
    // Footer
    'footer.about': 'Über',
    'footer.contact': 'Kontakt',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'Bedingungen',
    'footer.language': 'Sprache',
    'footer.rights': 'Alle Rechte vorbehalten',
    
    // Häufige Nachrichten
    'common.loading': 'Lädt...',
    'common.error': 'Ein Fehler ist aufgetreten',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.confirm': 'Bestätigen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.view': 'Ansicht',
    'common.share': 'Teilen',
    'common.copy': 'Kopieren',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.sort': 'Sortieren',
    'common.upload': 'Hochladen',
    'common.download': 'Herunterladen',
    'common.refresh': 'Aktualisieren',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Vorherige',
    'common.close': 'Schließen',
    'common.open': 'Öffnen',
    'common.show_more': 'Mehr anzeigen',
    'common.show_less': 'Weniger anzeigen',
  },
  zh: {
    // 导航和通用
    'nav.home': '首页',
    'nav.dashboard': '仪表板',
    'nav.news': '新闻',
    'nav.translate': '翻译',
    'nav.mindmap': '思维导图',
    'nav.weather': '天气',
    'nav.explore': '探索',
    'nav.login': '登录',
    'nav.logout': '退出',
    'nav.settings': '设置',
    'nav.profile': '个人资料',
    
    // 主页
    'hero.title': '欢迎来到LuvviX',
    'hero.subtitle': '满足您数字需求的一体化平台',
    'hero.description': '发现我们的创新应用程序生态系统，旨在提高您的生产力和创造力。',
    'hero.cta': '开始使用',
    'hero.learn_more': '了解更多',
    
    // 仪表板
    'dashboard.title': '仪表板',
    'dashboard.welcome': '欢迎',
    'dashboard.stats': '统计',
    'dashboard.recent': '最近活动',
    'dashboard.apps': '应用程序',
    'dashboard.quick_actions': '快速操作',
    'dashboard.settings': '设置',
    'dashboard.language': '语言',
    'dashboard.theme': '主题',
    'dashboard.notifications': '通知',
    'dashboard.privacy': '隐私',
    'dashboard.account': '账户',
    'dashboard.security': '安全',
    'dashboard.help': '帮助',
    'dashboard.about': '关于',
    
    // 新闻
    'news.title': '新闻',
    'news.subtitle': '保持信息更新',
    'news.description': '通过我们的智能策划系统发现来自世界各地的最新新闻。',
    'news.latest': '最新新闻',
    'news.search': '搜索新闻...',
    'news.loading': '加载中...',
    'news.error': '加载错误',
    'news.categories.all': '全部',
    'news.categories.technology': '技术',
    'news.categories.business': '商业',
    'news.categories.sports': '体育',
    'news.categories.entertainment': '娱乐',
    'news.categories.health': '健康',
    'news.categories.science': '科学',
    
    // 翻译
    'translate.title': 'AI翻译',
    'translate.subtitle': '智能翻译',
    'translate.description': '使用我们先进的AI即时翻译100多种语言的文本。',
    'translate.input_placeholder': '输入要翻译的文本...',
    'translate.output_placeholder': '翻译将显示在这里...',
    'translate.from': '从',
    'translate.to': '到',
    'translate.auto_detect': '自动检测',
    'translate.translate_btn': '翻译',
    'translate.copy': '复制',
    'translate.clear': '清除',
    
    // 思维导图
    'mindmap.title': 'AI思维导图',
    'mindmap.subtitle': '可视化您的想法',
    'mindmap.description': '在我们AI的帮助下创建交互式思维导图来组织您的想法。',
    'mindmap.input_placeholder': '描述您的主题或想法...',
    'mindmap.generate': '生成导图',
    'mindmap.loading': '生成中...',
    
    // 天气
    'weather.title': '天气',
    'weather.current': '当前天气',
    'weather.description': '查看当前天气条件和预报。',
    'weather.location': '位置',
    'weather.temperature': '温度',
    'weather.humidity': '湿度',
    'weather.wind': '风',
    'weather.pressure': '气压',
    
    // LuvviX Explore
    'explore.title': 'LuvviX探索',
    'explore.subtitle': '多模态AI搜索',
    'explore.description': '使用我们先进的AI探索网络、分析文件并获得智能答案。',
    'explore.search_placeholder': '搜索任何内容...',
    'explore.search_btn': '搜索',
    'explore.upload_file': '上传文件',
    'explore.recent_searches': '最近搜索',
    'explore.suggested_searches': '建议搜索',
    'explore.search_web': '网络搜索',
    'explore.search_videos': '视频搜索',
    'explore.search_images': '图片搜索',
    'explore.search_files': '文件搜索',
    'explore.ai_summary': 'AI摘要',
    'explore.ask_question': '提问',
    'explore.share_result': '分享结果',
    'explore.create_mindmap': '创建思维导图',
    'explore.translate_result': '翻译结果',
    'explore.create_form': '创建表单',
    'explore.create_agent': '创建AI代理',
    'explore.publish_center': '发布到中心',
    'explore.results_found': '找到结果',
    'explore.no_results': '未找到结果',
    'explore.loading': '搜索中...',
    'explore.categories.web': '网络',
    'explore.categories.videos': '视频',
    'explore.categories.images': '图片',
    'explore.categories.files': '文件',
    'explore.categories.discussions': '讨论',
    
    // 认证
    'auth.login': '登录',
    'auth.signup': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirm_password': '确认密码',
    'auth.forgot_password': '忘记密码？',
    'auth.no_account': '没有账户？',
    'auth.have_account': '已有账户？',
    'auth.login_success': '登录成功',
    'auth.signup_success': '注册成功',
    'auth.error': '认证错误',
    
    // 页脚
    'footer.about': '关于',
    'footer.contact': '联系',
    'footer.privacy': '隐私',
    'footer.terms': '条款',
    'footer.language': '语言',
    'footer.rights': '版权所有',
    
    // 常用信息
    'common.loading': '加载中...',
    'common.error': '发生错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.view': '查看',
    'common.share': '分享',
    'common.copy': '复制',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.sort': '排序',
    'common.upload': '上传',
    'common.download': '下载',
    'common.refresh': '刷新',
    'common.back': '返回',
    'common.next': '下一个',
    'common.previous': '上一个',
    'common.close': '关闭',
    'common.open': '打开',
    'common.show_more': '显示更多',
    'common.show_less': '显示更少',
  },
  ru: {
    // Навигация и общее
    'nav.home': 'Главная',
    'nav.dashboard': 'Панель',
    'nav.news': 'Новости',
    'nav.translate': 'Перевод',
    'nav.mindmap': 'Карта идей',
    'nav.weather': 'Погода',
    'nav.explore': 'Исследовать',
    'nav.login': 'Войти',
    'nav.logout': 'Выйти',
    'nav.settings': 'Настройки',
    'nav.profile': 'Профиль',
    
    // Главная страница
    'hero.title': 'Добро пожаловать в LuvviX',
    'hero.subtitle': 'Универсальная платформа для ваших цифровых потребностей',
    'hero.description': 'Откройте для себя нашу экосистему инновационных приложений, созданных для повышения вашей продуктивности и креативности.',
    'hero.cta': 'Начать',
    'hero.learn_more': 'Узнать больше',
    
    // Панель
    'dashboard.title': 'Панель',
    'dashboard.welcome': 'Добро пожаловать',
    'dashboard.stats': 'Статистика',
    'dashboard.recent': 'Недавние действия',
    'dashboard.apps': 'Приложения',
    'dashboard.quick_actions': 'Быстрые действия',
    'dashboard.settings': 'Настройки',
    'dashboard.language': 'Язык',
    'dashboard.theme': 'Тема',
    'dashboard.notifications': 'Уведомления',
    'dashboard.privacy': 'Конфиденциальность',
    'dashboard.account': 'Аккаунт',
    'dashboard.security': 'Безопасность',
    'dashboard.help': 'Помощь',
    'dashboard.about': 'О нас',
    
    // Новости
    'news.title': 'Новости',
    'news.subtitle': 'Будьте в курсе',
    'news.description': 'Откройте для себя последние новости со всего мира с помощью нашей интеллектуальной системы курирования.',
    'news.latest': 'Последние новости',
    'news.search': 'Поиск новостей...',
    'news.loading': 'Загрузка...',
    'news.error': 'Ошибка загрузки',
    'news.categories.all': 'Все',
    'news.categories.technology': 'Технологии',
    'news.categories.business': 'Бизнес',
    'news.categories.sports': 'Спорт',
    'news.categories.entertainment': 'Развлечения',
    'news.categories.health': 'Здоровье',
    'news.categories.science': 'Наука',
    
    // Перевод
    'translate.title': 'ИИ Перевод',
    'translate.subtitle': 'Умный перевод',
    'translate.description': 'Мгновенно переводите текст на более чем 100 языков с помощью нашего продвинутого ИИ.',
    'translate.input_placeholder': 'Введите текст для перевода...',
    'translate.output_placeholder': 'Перевод появится здесь...',
    'translate.from': 'С',
    'translate.to': 'На',
    'translate.auto_detect': 'Автоопределение',
    'translate.translate_btn': 'Перевести',
    'translate.copy': 'Копировать',
    'translate.clear': 'Очистить',
    
    // Карта идей
    'mindmap.title': 'ИИ Карта идей',
    'mindmap.subtitle': 'Визуализируйте свои идеи',
    'mindmap.description': 'Создавайте интерактивные карты идей с помощью нашего ИИ для организации ваших мыслей.',
    'mindmap.input_placeholder': 'Опишите вашу тему или идею...',
    'mindmap.generate': 'Создать карту',
    'mindmap.loading': 'Создание...',
    
    // Погода
    'weather.title': 'Погода',
    'weather.current': 'Текущая погода',
    'weather.description': 'Проверьте текущие погодные условия и прогнозы.',
    'weather.location': 'Местоположение',
    'weather.temperature': 'Температура',
    'weather.humidity': 'Влажность',
    'weather.wind': 'Ветер',
    'weather.pressure': 'Давление',
    
    // LuvviX Explore
    'explore.title': 'LuvviX Исследование',
    'explore.subtitle': 'Мультимодальный ИИ поиск',
    'explore.description': 'Исследуйте веб, анализируйте файлы и получайте умные ответы с помощью нашего продвинутого ИИ.',
    'explore.search_placeholder': 'Искать что угодно...',
    'explore.search_btn': 'Искать',
    'explore.upload_file': 'Загрузить файл',
    'explore.recent_searches': 'Недавние поиски',
    'explore.suggested_searches': 'Предлагаемые поиски',
    'explore.search_web': 'Поиск в вебе',
    'explore.search_videos': 'Поиск видео',
    'explore.search_images': 'Поиск изображений',
    'explore.search_files': 'Поиск файлов',
    'explore.ai_summary': 'ИИ резюме',
    'explore.ask_question': 'Задать вопрос',
    'explore.share_result': 'Поделиться результатом',
    'explore.create_mindmap': 'Создать карту идей',
    'explore.translate_result': 'Перевести результат',
    'explore.create_form': 'Создать форму',
    'explore.create_agent': 'Создать ИИ агента',
    'explore.publish_center': 'Опубликовать в центре',
    'explore.results_found': 'результатов найдено',
    'explore.no_results': 'Результаты не найдены',
    'explore.loading': 'Поиск...',
    'explore.categories.web': 'Веб',
    'explore.categories.videos': 'Видео',
    'explore.categories.images': 'Изображения',
    'explore.categories.files': 'Файлы',
    'explore.categories.discussions': 'Обсуждения',
    
    // Аутентификация
    'auth.login': 'Войти',
    'auth.signup': 'Регистрация',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.confirm_password': 'Подтвердить пароль',
    'auth.forgot_password': 'Забыли пароль?',
    'auth.no_account': 'Нет аккаунта?',
    'auth.have_account': 'Уже есть аккаунт?',
    'auth.login_success': 'Успешный вход',
    'auth.signup_success': 'Успешная регистрация',
    'auth.error': 'Ошибка аутентификации',
    
    // Подвал
    'footer.about': 'О нас',
    'footer.contact': 'Контакты',
    'footer.privacy': 'Конфиденциальность',
    'footer.terms': 'Условия',
    'footer.language': 'Язык',
    'footer.rights': 'Все права защищены',
    
    // Общие сообщения
    'common.loading': 'Загрузка...',
    'common.error': 'Произошла ошибка',
    'common.success': 'Успех',
    'common.cancel': 'Отмена',
    'common.confirm': 'Подтвердить',
    'common.save': 'Сохранить',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.view': 'Просмотр',
    'common.share': 'Поделиться',
    'common.copy': 'Копировать',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.sort': 'Сортировка',
    'common.upload': 'Загрузить',
    'common.download': 'Скачать',
    'common.refresh': 'Обновить',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.previous': 'Предыдущий',
    'common.close': 'Закрыть',
    'common.open': 'Открыть',
    'common.show_more': 'Показать больше',
    'common.show_less': 'Показать меньше',
  },
  it: {
    // Navigazione e generale
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.news': 'Notizie',
    'nav.translate': 'Traduci',
    'nav.mindmap': 'Mappa Mentale',
    'nav.weather': 'Meteo',
    'nav.explore': 'Esplora',
    'nav.login': 'Accedi',
    'nav.logout': 'Esci',
    'nav.settings': 'Impostazioni',
    'nav.profile': 'Profilo',
    
    // Homepage
    'hero.title': 'Benvenuto in LuvviX',
    'hero.subtitle': 'La piattaforma tutto-in-uno per le tue esigenze digitali',
    'hero.description': 'Scopri il nostro ecosistema di applicazioni innovative progettate per migliorare la tua produttività e creatività.',
    'hero.cta': 'Inizia',
    'hero.learn_more': 'Scopri di più',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Benvenuto',
    'dashboard.stats': 'Statistiche',
    'dashboard.recent': 'Attività Recenti',
    'dashboard.apps': 'Applicazioni',
    'dashboard.quick_actions': 'Azioni Rapide',
    'dashboard.settings': 'Impostazioni',
    'dashboard.language': 'Lingua',
    'dashboard.theme': 'Tema',
    'dashboard.notifications': 'Notifiche',
    'dashboard.privacy': 'Privacy',
    'dashboard.account': 'Account',
    'dashboard.security': 'Sicurezza',
    'dashboard.help': 'Aiuto',
    'dashboard.about': 'Info',
    
    // Notizie
    'news.title': 'Notizie',
    'news.subtitle': 'Rimani Informato',
    'news.description': 'Scopri le ultime notizie da tutto il mondo con il nostro sistema di curation intelligente.',
    'news.latest': 'Ultime Notizie',
    'news.search': 'Cerca notizie...',
    'news.loading': 'Caricamento...',
    'news.error': 'Errore di caricamento',
    'news.categories.all': 'Tutte',
    'news.categories.technology': 'Tecnologia',
    'news.categories.business': 'Business',
    'news.categories.sports': 'Sport',
    'news.categories.entertainment': 'Intrattenimento',
    'news.categories.health': 'Salute',
    'news.categories.science': 'Scienza',
    
    // Traduzione
    'translate.title': 'Traduzione IA',
    'translate.subtitle': 'Traduzione Intelligente',
    'translate.description': 'Traduci istantaneamente testo in oltre 100 lingue con la nostra IA avanzata.',
    'translate.input_placeholder': 'Inserisci il tuo testo da tradurre...',
    'translate.output_placeholder': 'La traduzione apparirà qui...',
    'translate.from': 'Da',
    'translate.to': 'A',
    'translate.auto_detect': 'Rilevamento automatico',
    'translate.translate_btn': 'Traduci',
    'translate.copy': 'Copia',
    'translate.clear': 'Cancella',
    
    // Mappa mentale
    'mindmap.title': 'Mappa Mentale IA',
    'mindmap.subtitle': 'Visualizza le Tue Idee',
    'mindmap.description': 'Crea mappe mentali interattive con l\'aiuto della nostra IA per organizzare i tuoi pensieri.',
    'mindmap.input_placeholder': 'Descrivi il tuo argomento o idea...',
    'mindmap.generate': 'Genera Mappa',
    'mindmap.loading': 'Generando...',
    
    // Meteo
    'weather.title': 'Meteo',
    'weather.current': 'Meteo Attuale',
    'weather.description': 'Controlla le condizioni meteorologiche attuali e le previsioni.',
    'weather.location': 'Posizione',
    'weather.temperature': 'Temperatura',
    'weather.humidity': 'Umidità',
    'weather.wind': 'Vento',
    'weather.pressure': 'Pressione',
    
    // LuvviX Explore
    'explore.title': 'LuvviX Explore',
    'explore.subtitle': 'Ricerca IA Multimodale',
    'explore.description': 'Esplora il web, analizza file e ottieni risposte intelligenti con la nostra IA avanzata.',
    'explore.search_placeholder': 'Cerca qualsiasi cosa...',
    'explore.search_btn': 'Cerca',
    'explore.upload_file': 'Carica File',
    'explore.recent_searches': 'Ricerche Recenti',
    'explore.suggested_searches': 'Ricerche Suggerite',
    'explore.search_web': 'Ricerca Web',
    'explore.search_videos': 'Ricerca Video',
    'explore.search_images': 'Ricerca Immagini',
    'explore.search_files': 'Ricerca File',
    'explore.ai_summary': 'Riassunto IA',
    'explore.ask_question': 'Fai una Domanda',
    'explore.share_result': 'Condividi Risultato',
    'explore.create_mindmap': 'Crea Mappa Mentale',
    'explore.translate_result': 'Traduci Risultato',
    'explore.create_form': 'Crea Modulo',
    'explore.create_agent': 'Crea Agente IA',
    'explore.publish_center': 'Pubblica su Center',
    'explore.results_found': 'risultati trovati',
    'explore.no_results': 'Nessun risultato trovato',
    'explore.loading': 'Cercando...',
    'explore.categories.web': 'Web',
    'explore.categories.videos': 'Video',
    'explore.categories.images': 'Immagini',
    'explore.categories.files': 'File',
    'explore.categories.discussions': 'Discussioni',
    
    // Autenticazione
    'auth.login': 'Accedi',
    'auth.signup': 'Registrati',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm_password': 'Conferma Password',
    'auth.forgot_password': 'Password dimenticata?',
    'auth.no_account': 'Nessun account?',
    'auth.have_account': 'Hai già un account?',
    'auth.login_success': 'Accesso riuscito',
    'auth.signup_success': 'Registrazione riuscita',
    'auth.error': 'Errore di autenticazione',
    
    // Footer
    'footer.about': 'Info',
    'footer.contact': 'Contatti',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Termini',
    'footer.language': 'Lingua',
    'footer.rights': 'Tutti i diritti riservati',
    
    // Messaggi comuni
    'common.loading': 'Caricamento...',
    'common.error': 'Si è verificato un errore',
    'common.success': 'Successo',
    'common.cancel': 'Annulla',
    'common.confirm': 'Conferma',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.view': 'Visualizza',
    'common.share': 'Condividi',
    'common.copy': 'Copia',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.sort': 'Ordina',
    'common.upload': 'Carica',
    'common.download': 'Scarica',
    'common.refresh': 'Aggiorna',
    'common.back': 'Indietro',
    'common.next': 'Avanti',
    'common.previous': 'Precedente',
    'common.close': 'Chiudi',
    'common.open': 'Apri',
    'common.show_more': 'Mostra di più',
    'common.show_less': 'Mostra meno',
  },
  ar: {
    // التنقل والعام
    'nav.home': 'الرئيسية',
    'nav.dashboard': 'لوحة التحكم',
    'nav.news': 'الأخبار',
    'nav.translate': 'ترجمة',
    'nav.mindmap': 'خريطة ذهنية',
    'nav.weather': 'الطقس',
    'nav.explore': 'استكشاف',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',
    'nav.settings': 'الإعدادات',
    'nav.profile': 'الملف الشخصي',
    
    // الصفحة الرئيسية
    'hero.title': 'مرحباً بك في LuvviX',
    'hero.subtitle': 'المنصة الشاملة لاحتياجاتك الرقمية',
    'hero.description': 'اكتشف نظامنا البيئي من التطبيقات المبتكرة المصممة لتعزيز إنتاجيتك وإبداعك.',
    'hero.cta': 'ابدأ الآن',
    'hero.learn_more': 'تعلم المزيد',
    
    // لوحة التحكم
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً',
    'dashboard.stats': 'الإحصائيات',
    'dashboard.recent': 'الأنشطة الحديثة',
    'dashboard.apps': 'التطبيقات',
    'dashboard.quick_actions': 'الإجراءات السريعة',
    'dashboard.settings': 'الإعدادات',
    'dashboard.language': 'اللغة',
    'dashboard.theme': 'السمة',
    'dashboard.notifications': 'الإشعارات',
    'dashboard.privacy': 'الخصوصية',
    'dashboard.account': 'الحساب',
    'dashboard.security': 'الأمان',
    'dashboard.help': 'المساعدة',
    'dashboard.about': 'حول',
    
    // الأخبار
    'news.title': 'الأخبار',
    'news.subtitle': 'ابق على اطلاع',
    'news.description': 'اكتشف آخر الأخبار من جميع أنحاء العالم مع نظام التنسيق الذكي لدينا.',
    'news.latest': 'أحدث الأخبار',
    'news.search': 'البحث في الأخبار...',
    'news.loading': 'جاري التحميل...',
    'news.error': 'خطأ في التحميل',
    'news.categories.all': 'الكل',
    'news.categories.technology': 'التكنولوجيا',
    'news.categories.business': 'الأعمال',
    'news.categories.sports': 'الرياضة',
    'news.categories.entertainment': 'الترفيه',
    'news.categories.health': 'الصحة',
    'news.categories.science': 'العلوم',
    
    // الترجمة
    'translate.title': 'ترجمة الذكاء الاصطناعي',
    'translate.subtitle': 'ترجمة ذكية',
    'translate.description': 'ترجم النص فوراً إلى أكثر من 100 لغة باستخدام الذكاء الاصطناعي المتقدم.',
    'translate.input_placeholder': 'أدخل النص للترجمة...',
    'translate.output_placeholder': 'ستظهر الترجمة هنا...',
    'translate.from': 'من',
    'translate.to': 'إلى',
    'translate.auto_detect': 'كشف تلقائي',
    'translate.translate_btn': 'ترجم',
    'translate.copy': 'نسخ',
    'translate.clear': 'مسح',
    
    // الخريطة الذهنية
    'mindmap.title': 'خريطة ذهنية بالذكاء الاصطناعي',
    'mindmap.subtitle': 'تصور أفكارك',
    'mindmap.description': 'إنشاء خرائط ذهنية تفاعلية بمساعدة الذكاء الاصطناعي لتنظيم أفكارك.',
    'mindmap.input_placeholder': 'صف موضوعك أو فكرتك...',
    'mindmap.generate': 'إنشاء خريطة',
    'mindmap.loading': 'جاري الإنشاء...',
    
    // الطقس
    'weather.title': 'الطقس',
    'weather.current': 'الطقس الحالي',
    'weather.description': 'تحقق من الأحوال الجوية الحالية والتوقعات.',
    'weather.location': 'الموقع',
    'weather.temperature': 'درجة الحرارة',
    'weather.humidity': 'الرطوبة',
    'weather.wind': 'الرياح',
    'weather.pressure': 'الضغط',
    
    // LuvviX Explore
    'explore.title': 'LuvviX استكشاف',
    'explore.subtitle': 'بحث ذكي متعدد الوسائط',
    'explore.description': 'استكشف الويب وحلل الملفات واحصل على إجابات ذكية باستخدام الذكاء الاصطناعي المتقدم.',
    'explore.search_placeholder': 'ابحث عن أي شيء...',
    'explore.search_btn': 'بحث',
    'explore.upload_file': 'رفع ملف',
    'explore.recent_searches': 'عمليات البحث الأخيرة',
    'explore.suggested_searches': 'عمليات البحث المقترحة',
    'explore.search_web': 'بحث الويب',
    'explore.search_videos': 'بحث الفيديو',
    'explore.search_images': 'بحث الصور',
    'explore.search_files': 'بحث الملفات',
    'explore.ai_summary': 'ملخص الذكاء الاصطناعي',
    'explore.ask_question': 'اطرح سؤالاً',
    'explore.share_result': 'مشاركة النتيجة',
    'explore.create_mindmap': 'إنشاء خريطة ذهنية',
    'explore.translate_result': 'ترجمة النتيجة',
    'explore.create_form': 'إنشاء نموذج',
    'explore.create_agent': 'إنشاء وكيل ذكي',
    'explore.publish_center': 'نشر في المركز',
    'explore.results_found': 'نتيجة موجودة',
    'explore.no_results': 'لم يتم العثور على نتائج',
    'explore.loading': 'جاري البحث...',
    'explore.categories.web': 'الويب',
    'explore.categories.videos': 'الفيديو',
    'explore.categories.images': 'الصور',
    'explore.categories.files': 'الملفات',
    'explore.categories.discussions': 'المناقشات',
    
    // المصادقة
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'التسجيل',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirm_password': 'تأكيد كلمة المرور',
    'auth.forgot_password': 'نسيت كلمة المرور؟',
    'auth.no_account': 'ليس لديك حساب؟',
    'auth.have_account': 'هل لديك حساب بالفعل؟',
    'auth.login_success': 'تم تسجيل الدخول بنجاح',
    'auth.signup_success': 'تم التسجيل بنجاح',
    'auth.error': 'خطأ في المصادقة',
    
    // التذييل
    'footer.about': 'حول',
    'footer.contact': 'اتصال',
    'footer.privacy': 'الخصوصية',
    'footer.terms': 'الشروط',
    'footer.language': 'اللغة',
    'footer.rights': 'جميع الحقوق محفوظة',
    
    // الرسائل الشائعة
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تحرير',
    'common.view': 'عرض',
    'common.share': 'مشاركة',
    'common.copy': 'نسخ',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.upload': 'رفع',
    'common.download': 'تحميل',
    'common.refresh': 'تحديث',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.close': 'إغلاق',
    'common.open': 'فتح',
    'common.show_more': 'عرض المزيد',
    'common.show_less': 'عرض أقل',
  },
};

// Détection automatique de la langue du navigateur
const detectBrowserLanguage = (): Language => {
  const browserLang = navigator.language.split('-')[0] as Language;
  const supportedLanguages: Language[] = ['fr', 'en', 'es', 'pt', 'de', 'zh', 'ru', 'it', 'ar'];
  
  if (supportedLanguages.includes(browserLang)) {
    return browserLang;
  }
  
  // Langue par défaut
  return 'fr';
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('luvvix-language') as Language;
    return savedLanguage || detectBrowserLanguage();
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('luvvix-language', lang);
    
    // Mettre à jour l'attribut lang du document
    document.documentElement.lang = lang;
    
    // Mettre à jour la direction du texte pour l'arabe
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        break;
      }
    }
    
    // Fallback vers l'anglais si la clé n'est pas trouvée
    if (!value && language !== 'en') {
      let fallbackValue: any = translations.en;
      for (const k of keys) {
        if (fallbackValue && typeof fallbackValue === 'object') {
          fallbackValue = fallbackValue[k];
        } else {
          break;
        }
      }
      value = fallbackValue;
    }
    
    return typeof value === 'string' ? value : key;
  };

  // Mettre à jour les attributs du document au montage
  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
