import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface Language {
  code: string;
  name: string;
  flag: string;
}

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  languages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languages: Language[] = [
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
];

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.ecosystem': 'Écosystème',
    'nav.docs': 'Documentation',
    'nav.news': 'Actualités',
    'nav.support': 'Support',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    'nav.dashboard': 'Tableau de bord',
    'nav.logout': 'Déconnexion',
    'nav.profile': 'Profil',
    'nav.settings': 'Paramètres',

    // Apps
    'app.aiStudio': 'AI Studio',
    'app.cloud': 'Cloud',
    'app.translate': 'Translate',
    'app.forms': 'Forms',
    'app.mindmap': 'MindMap',
    'app.news': 'News',
    'app.weather': 'Météo',
    'app.analytics': 'Analytics',
    'app.crawler': 'Crawler',
    'app.docs': 'Docs Generator',
    'app.learn': 'Learn',
    'app.center': 'Center',
    'app.codeStudio': 'Code Studio',

    // Hero Section
    'hero.title': 'LuvviX ID',
    'hero.subtitle': 'Votre identité numérique',
    'hero.description': 'Un système d\'authentification unique et sécurisé pour accéder à l\'ensemble de notre écosystème technologique made in Cameroun avec amour',
    'hero.createAccount': 'Créer un compte',
    'hero.discoverEcosystem': 'Découvrir l\'écosystème',
    'hero.secureAuth': 'Authentification sécurisée',
    'hero.instantConnection': 'Connexion instantanée',
    'hero.multiplatform': 'Compatible multiplateforme',
    'hero.devApi': 'API pour développeurs',
    'hero.aiStudioNew': 'LuvviX AI Studio',
    'hero.aiStudioDesc': 'Créez vos propres agents IA personnalisés en quelques minutes. Propulsé par la technologie Cerebras.',
    'hero.aiAdvanced': 'IA avancée',
    'hero.fast': 'Rapide',
    'hero.secure': 'Sécurisé',
    'hero.createAI': 'Créer votre assistant IA',

    // Dashboard
    'dashboard.welcome': 'Bienvenue',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.recentActivity': 'Activité récente',
    'dashboard.connectedApps': 'Applications connectées',
    'dashboard.accountSettings': 'Paramètres du compte',
    'dashboard.security': 'Sécurité',
    'dashboard.notifications': 'Notifications',
    'dashboard.apiKeys': 'Clés API',
    'dashboard.viewProfile': 'Voir le profil',
    'dashboard.manageApps': 'Gérer les applications',
    'dashboard.viewActivity': 'Voir l\'activité',
    'dashboard.securitySettings': 'Paramètres de sécurité',
    'dashboard.overview': 'Aperçu',
    'dashboard.profile': 'Profil',
    'dashboard.apps': 'Applications',
    'dashboard.activity': 'Activité',
    'dashboard.settings': 'Paramètres',
    'dashboard.language': 'Langue',
    'dashboard.theme': 'Thème',
    'dashboard.privacy': 'Confidentialité',
    'dashboard.twoFactor': 'Authentification à deux facteurs',
    'dashboard.connectedDevices': 'Appareils connectés',
    'dashboard.loginHistory': 'Historique de connexion',
    'dashboard.dataExport': 'Export des données',
    'dashboard.deleteAccount': 'Supprimer le compte',

    // Footer
    'footer.description': 'Votre écosystème numérique complet, sécurisé et innovant.',
    'footer.products': 'Produits',
    'footer.resources': 'Ressources',
    'footer.legal': 'Légal',
    'footer.documentation': 'Documentation',
    'footer.api': 'API',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2024 LuvviX. Tous droits réservés.',
    'footer.availableLanguages': 'Langues disponibles',

    // Forms
    'forms.title': 'LuvviX Forms',
    'forms.subtitle': 'Criez et partagez facilement des formulaires',
    'forms.description': 'Créez des formulaires interactifs et collectez des réponses en temps réel avec notre plateforme intuitive.',
    'forms.createForm': 'Créer un formulaire',
    'forms.viewForms': 'Voir les formulaires',
    'forms.myForms': 'Mes formulaires',
    'forms.responses': 'Réponses',
    'forms.analytics': 'Analyses',
    'forms.settings': 'Paramètres',

    // News
    'news.title': 'LuvviX News',
    'news.subtitle': 'Restez informé',
    'news.description': 'Restez informé avec des actualités personnalisées provenant de sources diverses à travers le web.',
    'news.categories': 'Catégories',
    'news.trending': 'Tendances',
    'news.latest': 'Dernières actualités',
    'news.search': 'Rechercher des actualités...',

    // Weather
    'weather.title': 'LuvviX Météo',
    'weather.current': 'Météo actuelle',
    'weather.description': 'Consultez la météo en temps réel pour votre emplacement actuel',

    // AI Studio
    'aiStudio.title': 'LuvviX AI Studio',
    'aiStudio.subtitle': 'Créez vos propres agents IA',
    'aiStudio.description': 'Plataforme révolutionnaire pour créer, entraîner et déployer vos propres agents d\'intelligence artificielle.',
    'aiStudio.createAgent': 'Créer un agent',
    'aiStudio.myAgents': 'Mes agents',
    'aiStudio.templates': 'Modèles',
    'aiStudio.marketplace': 'Marketplace',

    // Translate
    'translate.title': 'LuvviX Translate',
    'translate.subtitle': 'Traduction IA en temps réel',
    'translate.description': 'Traduisez instantanément dans plus de 50 langues avec l\'intelligence artificielle avancée.',
    'translate.from': 'De',
    'translate.to': 'A',
    'translate.translate': 'Traduire',
    'translate.listening': 'Écoute...',
    'translate.speak': 'Parler',

    // MindMap
    'mindmap.title': 'LuvviX MindMap',
    'mindmap.subtitle': 'Mapes mentales IA intelligentes',
    'mindmap.description': 'Créez des mapes mentales intelligentes avec l\'IA pour organiser vos idées, stimuler votre créativité et structurer vos connaissances.',
    'mindmap.create': 'Créer une carte',
    'mindmap.templates': 'Modèles',
    'mindmap.myMaps': 'Mes cartes',

    // Cloud
    'cloud.title': 'LuvviX Cloud',
    'cloud.subtitle': 'Stockage cloud sécurisé',
    'cloud.description': 'Stockez, synchronisez et partagez vos fichiers en toute sécurité avec notre solution cloud décentralisée.',
    'cloud.upload': 'Télécharger',
    'cloud.myFiles': 'Mes fichiers',
    'cloud.shared': 'Partagé',
    'cloud.recent': 'Récent',

    // Code Studio
    'codeStudio.title': 'LuvviX Code Studio',
    'codeStudio.subtitle': 'Studio de développement IA',
    'codeStudio.description': 'Studio de développement révolutionnaire avec génération intelligente et optimisation de code alimenté par LuvviX AI.',
    'codeStudio.generate': 'Générer',
    'codeStudio.optimize': 'Optimiser',
    'codeStudio.analyze': 'Analyser',

    // Authentication
    'auth.login': 'Connexion',
    'auth.signup': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.forgotPassword': 'Mot de passe oublié ?',
    'auth.noAccount': 'Pas de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.signupHere': 'Inscrivez-vous ici',
    'auth.loginHere': 'Connectez-vous ici',
    'auth.or': 'ou',
    'auth.googleLogin': 'Continuer avec Google',
    'auth.githubLogin': 'Continuer avec GitHub',

    // Common
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.share': 'Partager',
    'common.copy': 'Copier',
    'common.download': 'Télécharger',
    'common.upload': 'Télécharger',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.refresh': 'Actualiser',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.close': 'Fermer',
    'common.open': 'Ouvrir',
    'common.create': 'Créer',
    'common.new': 'Nouveau',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.ecosystem': 'Ecosystem',
    'nav.docs': 'Documentation',
    'nav.news': 'News',
    'nav.support': 'Support',
    'nav.login': 'Login',
    'nav.signup': 'Sign up',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',

    // Apps
    'app.aiStudio': 'AI Studio',
    'app.cloud': 'Cloud',
    'app.translate': 'Translate',
    'app.forms': 'Forms',
    'app.mindmap': 'MindMap',
    'app.news': 'News',
    'app.weather': 'Weather',
    'app.analytics': 'Analytics',
    'app.crawler': 'Crawler',
    'app.docs': 'Docs Generator',
    'app.learn': 'Learn',
    'app.center': 'Center',
    'app.codeStudio': 'Code Studio',

    // Hero Section
    'hero.title': 'LuvviX ID',
    'hero.subtitle': 'Your digital identity',
    'hero.description': 'A unique and secure authentication system to access our entire technology ecosystem made in Cameroon with love',
    'hero.createAccount': 'Create account',
    'hero.discoverEcosystem': 'Discover ecosystem',
    'hero.secureAuth': 'Secure authentication',
    'hero.instantConnection': 'Instant connection',
    'hero.multiplatform': 'Cross-platform compatible',
    'hero.devApi': 'Developer API',
    'hero.aiStudioNew': 'LuvviX AI Studio',
    'hero.aiStudioDesc': 'Create your own custom AI agents in minutes. Powered by Cerebras technology.',
    'hero.aiAdvanced': 'Advanced AI',
    'hero.fast': 'Fast',
    'hero.secure': 'Secure',
    'hero.createAI': 'Create your AI assistant',

    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.quickActions': 'Quick actions',
    'dashboard.recentActivity': 'Recent activity',
    'dashboard.connectedApps': 'Connected apps',
    'dashboard.accountSettings': 'Account settings',
    'dashboard.security': 'Security',
    'dashboard.notifications': 'Notifications',
    'dashboard.apiKeys': 'API Keys',
    'dashboard.viewProfile': 'View profile',
    'dashboard.manageApps': 'Manage apps',
    'dashboard.viewActivity': 'View activity',
    'dashboard.securitySettings': 'Security settings',
    'dashboard.overview': 'Overview',
    'dashboard.profile': 'Profile',
    'dashboard.apps': 'Apps',
    'dashboard.activity': 'Activity',
    'dashboard.settings': 'Settings',
    'dashboard.language': 'Language',
    'dashboard.theme': 'Theme',
    'dashboard.privacy': 'Privacy',
    'dashboard.twoFactor': 'Two-factor authentication',
    'dashboard.connectedDevices': 'Connected devices',
    'dashboard.loginHistory': 'Login history',
    'dashboard.dataExport': 'Data export',
    'dashboard.deleteAccount': 'Delete account',

    // Footer
    'footer.description': 'Your complete, secure and innovative digital ecosystem.',
    'footer.products': 'Products',
    'footer.resources': 'Resources',
    'footer.legal': 'Legal',
    'footer.documentation': 'Documentation',
    'footer.api': 'API',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2024 LuvviX. All rights reserved.',
    'footer.availableLanguages': 'Available languages',

    // Forms
    'forms.title': 'LuvviX Forms',
    'forms.subtitle': 'Create and share forms easily',
    'forms.description': 'Create interactive forms and collect responses in real-time with our intuitive platform.',
    'forms.createForm': 'Create form',
    'forms.viewForms': 'View forms',
    'forms.myForms': 'My forms',
    'forms.responses': 'Responses',
    'forms.analytics': 'Analytics',
    'forms.settings': 'Settings',

    // News
    'news.title': 'LuvviX News',
    'news.subtitle': 'Stay informed',
    'news.description': 'Stay informed with personalized news from various sources across the web.',
    'news.categories': 'Categories',
    'news.trending': 'Trending',
    'news.latest': 'Latest news',
    'news.search': 'Search news...',

    // Weather
    'weather.title': 'LuvviX Weather',
    'weather.current': 'Current weather',
    'weather.description': 'Check real-time weather for your current location',

    // AI Studio
    'aiStudio.title': 'LuvviX AI Studio',
    'aiStudio.subtitle': 'Create your own AI agents',
    'aiStudio.description': 'Revolutionary platform to create, train and deploy your own artificial intelligence agents.',
    'aiStudio.createAgent': 'Create agent',
    'aiStudio.myAgents': 'My agents',
    'aiStudio.templates': 'Templates',
    'aiStudio.marketplace': 'Marketplace',

    // Translate
    'translate.title': 'LuvviX Translate',
    'translate.subtitle': 'Real-time AI translation',
    'translate.description': 'Translate instantly in over 50 languages with advanced artificial intelligence.',
    'translate.from': 'From',
    'translate.to': 'To',
    'translate.translate': 'Translate',
    'translate.listening': 'Listening...',
    'translate.speak': 'Speak',

    // MindMap
    'mindmap.title': 'LuvviX MindMap',
    'mindmap.subtitle': 'Smart AI mind maps',
    'mindmap.description': 'Create smart mind maps with AI to organize your ideas, stimulate creativity and structure knowledge.',
    'mindmap.create': 'Create map',
    'mindmap.templates': 'Templates',
    'mindmap.myMaps': 'My maps',

    // Cloud
    'cloud.title': 'LuvviX Cloud',
    'cloud.subtitle': 'Secure cloud storage',
    'cloud.description': 'Store, sync and share your files securely with our decentralized cloud solution.',
    'cloud.upload': 'Upload',
    'cloud.myFiles': 'My files',
    'cloud.shared': 'Shared',
    'cloud.recent': 'Recent',

    // Code Studio
    'codeStudio.title': 'LuvviX Code Studio',
    'codeStudio.subtitle': 'AI development studio',
    'codeStudio.description': 'Revolutionary development studio with intelligent code generation and optimization powered by LuvviX AI.',
    'codeStudio.generate': 'Generate',
    'codeStudio.optimize': 'Optimize',
    'codeStudio.analyze': 'Analyze',

    // Authentication
    'auth.login': 'Login',
    'auth.signup': 'Sign up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.firstName': 'First name',
    'auth.lastName': 'Last name',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': 'No account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.signupHere': 'Sign up here',
    'auth.loginHere': 'Login here',
    'auth.or': 'or',
    'auth.googleLogin': 'Continue with Google',
    'auth.githubLogin': 'Continue with GitHub',

    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.create': 'Create',
    'common.new': 'New',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.ecosystem': 'Ecosistema',
    'nav.docs': 'Documentación',
    'nav.news': 'Noticias',
    'nav.support': 'Soporte',
    'nav.login': 'Iniciar sesión',
    'nav.signup': 'Registrarse',
    'nav.dashboard': 'Panel',
    'nav.logout': 'Cerrar sesión',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',

    // Apps
    'app.aiStudio': 'AI Studio',
    'app.cloud': 'Nube',
    'app.translate': 'Traductor',
    'app.forms': 'Formularios',
    'app.mindmap': 'Mapa Mental',
    'app.news': 'Noticias',
    'app.weather': 'Clima',
    'app.analytics': 'Analíticas',
    'app.crawler': 'Rastreador',
    'app.docs': 'Generador de Docs',
    'app.learn': 'Aprender',
    'app.center': 'Centro',
    'app.codeStudio': 'Estudio de Código',

    // Hero Section
    'hero.title': 'LuvviX ID',
    'hero.subtitle': 'Tu identidad digital',
    'hero.description': 'Un sistema de autenticación único y seguro para acceder a todo nuestro ecosistema tecnológico hecho en Camerún con amor',
    'hero.createAccount': 'Crear cuenta',
    'hero.discoverEcosystem': 'Descubrir ecosistema',
    'hero.secureAuth': 'Autenticación segura',
    'hero.instantConnection': 'Conexión instantánea',
    'hero.multiplatform': 'Compatible multiplataforma',
    'hero.devApi': 'API para desarrolladores',
    'hero.aiStudioNew': 'LuvviX AI Studio',
    'hero.aiStudioDesc': 'Crea tus propios agentes de IA personalizados en minutos. Potenciado por tecnología Cerebras.',
    'hero.aiAdvanced': 'IA avanzada',
    'hero.fast': 'Rápido',
    'hero.secure': 'Seguro',
    'hero.createAI': 'Crear tu asistente IA',

    // Dashboard
    'dashboard.welcome': 'Bienvenido',
    'dashboard.quickActions': 'Acciones rápidas',
    'dashboard.recentActivity': 'Actividad reciente',
    'dashboard.connectedApps': 'Apps conectadas',
    'dashboard.accountSettings': 'Configuración de cuenta',
    'dashboard.security': 'Seguridad',
    'dashboard.notifications': 'Notificaciones',
    'dashboard.apiKeys': 'Claves API',
    'dashboard.viewProfile': 'Ver perfil',
    'dashboard.manageApps': 'Gestionar apps',
    'dashboard.viewActivity': 'Ver actividad',
    'dashboard.securitySettings': 'Configuración de seguridad',
    'dashboard.overview': 'Resumen',
    'dashboard.profile': 'Perfil',
    'dashboard.apps': 'Aplicaciones',
    'dashboard.activity': 'Actividad',
    'dashboard.settings': 'Configuración',
    'dashboard.language': 'Idioma',
    'dashboard.theme': 'Tema',
    'dashboard.privacy': 'Privacidad',
    'dashboard.twoFactor': 'Autenticación de dos factores',
    'dashboard.connectedDevices': 'Dispositivos conectados',
    'dashboard.loginHistory': 'Historial de inicio de sesión',
    'dashboard.dataExport': 'Exportar datos',
    'dashboard.deleteAccount': 'Eliminar cuenta',

    // Footer
    'footer.description': 'Tu ecosistema digital completo, seguro e innovador.',
    'footer.products': 'Productos',
    'footer.resources': 'Recursos',
    'footer.legal': 'Legal',
    'footer.documentation': 'Documentación',
    'footer.api': 'API',
    'footer.privacy': 'Privacidad',
    'footer.terms': 'Términos de servicio',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2024 LuvviX. Todos los derechos reservados.',
    'footer.availableLanguages': 'Idiomas disponibles',

    // Forms
    'forms.title': 'LuvviX Forms',
    'forms.subtitle': 'Crea y comparte formularios fácilmente',
    'forms.description': 'Crea formularios interactivos y recopila respuestas en tiempo real con nuestra plataforma intuitiva.',
    'forms.createForm': 'Crear formulario',
    'forms.viewForms': 'Ver formularios',
    'forms.myForms': 'Mis formularios',
    'forms.responses': 'Respuestas',
    'forms.analytics': 'Análisis',
    'forms.settings': 'Configuración',

    // News
    'news.title': 'LuvviX News',
    'news.subtitle': 'Mantente informado',
    'news.description': 'Mantente informado con noticias personalizadas de diversas fuentes en la web.',
    'news.categories': 'Categorías',
    'news.trending': 'Tendencias',
    'news.latest': 'Últimas noticias',
    'news.search': 'Buscar noticias...',

    // Weather
    'weather.title': 'LuvviX Clima',
    'weather.current': 'Clima actual',
    'weather.description': 'Consulta el clima en tiempo real para tu ubicación actual',

    // AI Studio
    'aiStudio.title': 'LuvviX AI Studio',
    'aiStudio.subtitle': 'Crea tus propios agentes IA',
    'aiStudio.description': 'Plataforma revolucionaria para crear, entrenar y desplegar tus propios agentes de inteligencia artificial.',
    'aiStudio.createAgent': 'Crear agente',
    'aiStudio.myAgents': 'Mis agentes',
    'aiStudio.templates': 'Plantillas',
    'aiStudio.marketplace': 'Mercado',

    // Translate
    'translate.title': 'LuvviX Translate',
    'translate.subtitle': 'Traducción IA en tiempo real',
    'translate.description': 'Traduce instantáneamente en más de 50 idiomas con inteligencia artificial avanzada.',
    'translate.from': 'De',
    'translate.to': 'A',
    'translate.translate': 'Traducir',
    'translate.listening': 'Escuchando...',
    'translate.speak': 'Hablar',

    // MindMap
    'mindmap.title': 'LuvviX MindMap',
    'mindmap.subtitle': 'Mapas mentales IA inteligentes',
    'mindmap.description': 'Crea mapas mentales inteligentes con IA para organizar tus ideas, estimular la creatividad y estructurar el conocimiento.',
    'mindmap.create': 'Crear mapa',
    'mindmap.templates': 'Plantillas',
    'mindmap.myMaps': 'Mis mapas',

    // Cloud
    'cloud.title': 'LuvviX Cloud',
    'cloud.subtitle': 'Almacenamiento en la nube seguro',
    'cloud.description': 'Almacena, sincroniza y comparte tus archivos de forma segura con nuestra solución de nube descentralizada.',
    'cloud.upload': 'Subir',
    'cloud.myFiles': 'Mis archivos',
    'cloud.shared': 'Compartido',
    'cloud.recent': 'Reciente',

    // Code Studio
    'codeStudio.title': 'LuvviX Code Studio',
    'codeStudio.subtitle': 'Estudio de desarrollo IA',
    'codeStudio.description': 'Estudio de desarrollo revolucionario con generación inteligente y optimización de código impulsado por LuvviX AI.',
    'codeStudio.generate': 'Generar',
    'codeStudio.optimize': 'Optimizar',
    'codeStudio.analyze': 'Analizar',

    // Authentication
    'auth.login': 'Iniciar sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.firstName': 'Nombre',
    'auth.lastName': 'Apellido',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes una cuenta?',
    'auth.signupHere': 'Regístrate aquí',
    'auth.loginHere': 'Inicia sesión aquí',
    'auth.or': 'o',
    'auth.googleLogin': 'Continuar con Google',
    'auth.githubLogin': 'Continuar con GitHub',

    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.share': 'Compartir',
    'common.copy': 'Copiar',
    'common.download': 'Descargar',
    'common.upload': 'Subir',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.refresh': 'Actualizar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.close': 'Cerrar',
    'common.open': 'Abrir',
    'common.create': 'Crear',
    'common.new': 'Nuevo',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.ecosystem': 'Ecossistema',
    'nav.docs': 'Documentação',
    'nav.news': 'Notícias',
    'nav.support': 'Suporte',
    'nav.login': 'Entrar',
    'nav.signup': 'Cadastrar',
    'nav.dashboard': 'Painel',
    'nav.logout': 'Sair',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configurações',

    // Apps
    'app.aiStudio': 'AI Studio',
    'app.cloud': 'Nuvem',
    'app.translate': 'Tradutor',
    'app.forms': 'Formulários',
    'app.mindmap': 'Mapa Mental',
    'app.news': 'Notícias',
    'app.weather': 'Clima',
    'app.analytics': 'Analytics',
    'app.crawler': 'Crawler',
    'app.docs': 'Gerador de Docs',
    'app.learn': 'Aprender',
    'app.center': 'Centro',
    'app.codeStudio': 'Estúdio de Código',

    // Hero Section
    'hero.title': 'LuvviX ID',
    'hero.subtitle': 'Sua identidade digital',
    'hero.description': 'Um sistema de autenticação único e seguro para acessar todo o nosso ecossistema tecnológico feito em Camarões com amor',
    'hero.createAccount': 'Criar conta',
    'hero.discoverEcosystem': 'Descobrir ecossistema',
    'hero.secureAuth': 'Autenticação segura',
    'hero.instantConnection': 'Conexão instantânea',
    'hero.multiplatform': 'Compatível multiplataforma',
    'hero.devApi': 'API para desenvolvedores',
    'hero.aiStudioNew': 'LuvviX AI Studio',
    'hero.aiStudioDesc': 'Crie seus próprios agentes de IA personalizados em minutos. Alimentado pela tecnologia Cerebras.',
    'hero.aiAdvanced': 'IA avançada',
    'hero.fast': 'Rápido',
    'hero.secure': 'Seguro',
    'hero.createAI': 'Criar seu assistente IA',

    // Dashboard
    'dashboard.welcome': 'Bem-vindo',
    'dashboard.quickActions': 'Ações rápidas',
    'dashboard.recentActivity': 'Atividade recente',
    'dashboard.connectedApps': 'Apps conectados',
    'dashboard.accountSettings': 'Configurações da conta',
    'dashboard.security': 'Segurança',
    'dashboard.notifications': 'Notificações',
    'dashboard.apiKeys': 'Chaves API',
    'dashboard.viewProfile': 'Ver perfil',
    'dashboard.manageApps': 'Gerenciar apps',
    'dashboard.viewActivity': 'Ver atividade',
    'dashboard.securitySettings': 'Configurações de segurança',
    'dashboard.overview': 'Visão geral',
    'dashboard.profile': 'Perfil',
    'dashboard.apps': 'Aplicativos',
    'dashboard.activity': 'Atividade',
    'dashboard.settings': 'Configurações',
    'dashboard.language': 'Idioma',
    'dashboard.theme': 'Tema',
    'dashboard.privacy': 'Privacidade',
    'dashboard.twoFactor': 'Autenticação de dois fatores',
    'dashboard.connectedDevices': 'Dispositivos conectados',
    'dashboard.loginHistory': 'Histórico de login',
    'dashboard.dataExport': 'Exportar dados',
    'dashboard.deleteAccount': 'Excluir conta',

    // Footer
    'footer.description': 'Seu ecossistema digital completo, seguro e inovador.',
    'footer.products': 'Produtos',
    'footer.resources': 'Recursos',
    'footer.legal': 'Legal',
    'footer.documentation': 'Documentação',
    'footer.api': 'API',
    'footer.privacy': 'Privacidade',
    'footer.terms': 'Termos de serviço',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2024 LuvviX. Todos os direitos reservados.',
    'footer.availableLanguages': 'Idiomas disponíveis',

    // Forms
    'forms.title': 'LuvviX Forms',
    'forms.subtitle': 'Crie e compartilhe formulários facilmente',
    'forms.description': 'Crie formulários interativos e colete respostas em tempo real com nossa plataforma intuitiva.',
    'forms.createForm': 'Criar formulário',
    'forms.viewForms': 'Ver formulários',
    'forms.myForms': 'Meus formulários',
    'forms.responses': 'Respostas',
    'forms.analytics': 'Análises',
    'forms.settings': 'Configurações',

    // News
    'news.title': 'LuvviX News',
    'news.subtitle': 'Mantenha-se informado',
    'news.description': 'Mantenha-se informado com notícias personalizadas de várias fontes na web.',
    'news.categories': 'Categorias',
    'news.trending': 'Tendências',
    'news.latest': 'Últimas notícias',
    'news.search': 'Buscar notícias...',

    // Weather
    'weather.title': 'LuvviX Clima',
    'weather.current': 'Clima atual',
    'weather.description': 'Consulte o clima em tempo real para sua localização atual',

    // AI Studio
    'aiStudio.title': 'LuvviX AI Studio',
    'aiStudio.subtitle': 'Crie seus próprios agentes IA',
    'aiStudio.description': 'Plataforma revolucionária para criar, treinar e implantar seus próprios agentes de inteligência artificial.',
    'aiStudio.createAgent': 'Criar agente',
    'aiStudio.myAgents': 'Meus agentes',
    'aiStudio.templates': 'Modelos',
    'aiStudio.marketplace': 'Marketplace',

    // Translate
    'translate.title': 'LuvviX Translate',
    'translate.subtitle': 'Tradução IA em tempo real',
    'translate.description': 'Traduza instantaneamente em mais de 50 idiomas com inteligência artificial avançada.',
    'translate.from': 'De',
    'translate.to': 'Para',
    'translate.translate': 'Traduzir',
    'translate.listening': 'Ouvindo...',
    'translate.speak': 'Falar',

    // MindMap
    'mindmap.title': 'LuvviX MindMap',
    'mindmap.subtitle': 'Mapas mentais IA inteligentes',
    'mindmap.description': 'Crie mapas mentais inteligentes com IA para organizar suas ideias, estimular a criatividade e estruturar conhecimento.',
    'mindmap.create': 'Criar mapa',
    'mindmap.templates': 'Modelos',
    'mindmap.myMaps': 'Meus mapas',

    // Cloud
    'cloud.title': 'LuvviX Cloud',
    'cloud.subtitle': 'Armazenamento em nuvem seguro',
    'cloud.description': 'Armazene, sincronize e compartilhe seus arquivos com segurança com nossa solução de nuvem descentralizada.',
    'cloud.upload': 'Upload',
    'cloud.myFiles': 'Meus arquivos',
    'cloud.shared': 'Compartilhado',
    'cloud.recent': 'Recente',

    // Code Studio
    'codeStudio.title': 'LuvviX Code Studio',
    'codeStudio.subtitle': 'Estúdio de desenvolvimento IA',
    'codeStudio.description': 'Estúdio de desenvolvimento revolucionário com geração inteligente e otimização de código alimentado por LuvviX AI.',
    'codeStudio.generate': 'Gerar',
    'codeStudio.optimize': 'Otimizar',
    'codeStudio.analyze': 'Analisar',

    // Authentication
    'auth.login': 'Entrar',
    'auth.signup': 'Cadastrar',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar senha',
    'auth.firstName': 'Nome',
    'auth.lastName': 'Sobrenome',
    'auth.forgotPassword': 'Esqueceu a senha?',
    'auth.noAccount': 'Não tem conta?',
    'auth.hasAccount': 'Já tem uma conta?',
    'auth.signupHere': 'Cadastre-se aqui',
    'auth.loginHere': 'Entre aqui',
    'auth.or': 'ou',
    'auth.googleLogin': 'Continuar com Google',
    'auth.githubLogin': 'Continuar com GitHub',

    // Common
    'common.loading': 'Carregando...',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.share': 'Compartilhar',
    'common.copy': 'Copiar',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.refresh': 'Atualizar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.close': 'Fechar',
    'common.open': 'Abrir',
    'common.create': 'Criar',
    'common.new': 'Novo',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.ecosystem': 'Ökosystem',
    'nav.docs': 'Dokumentation',
    'nav.news': 'Nachrichten',
    'nav.support': 'Support',
    'nav.login': 'Anmelden',
    'nav.signup': 'Registrieren',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Abmelden',
    'nav.profile': 'Profil',
    'nav.settings': 'Einstellungen',

    // Apps
    'app.aiStudio': 'AI Studio',
    'app.cloud': 'Cloud',
    'app.translate': 'Übersetzer',
    'app.forms': 'Formulare',
    'app.mindmap': 'Mind Map',
    'app.news': 'Nachrichten',
    'app.weather': 'Wetter',
    'app.analytics': 'Analytics',
    'app.crawler': 'Crawler',
    'app.docs': 'Docs Generator',
    'app.learn': 'Lernen',
    'app.center': 'Zentrum',
    'app.codeStudio': 'Code Studio',

    // Hero Section
    'hero.title': 'LuvviX ID',
    'hero.subtitle': 'Ihre digitale Identität',
    'hero.description': 'Ein einzigartiges und sicheres Authentifizierungssystem für den Zugang zu unserem gesamten Technologie-Ökosystem, mit Liebe in Kamerun entwickelt',
    'hero.createAccount': 'Konto erstellen',
    'hero.discoverEcosystem': 'Ökosystem entdecken',
    'hero.secureAuth': 'Sichere Authentifizierung',
    'hero.instantConnection': 'Sofortige Verbindung',
    'hero.multiplatform': 'Plattformübergreifend kompatibel',
    'hero.devApi': 'Entwickler-API',
    'hero.aiStudioNew': 'LuvviX AI Studio',
    'hero.aiStudioDesc': 'Erstellen Sie Ihre eigenen benutzerdefinierten KI-Agenten in Minuten. Angetrieben von Cerebras-Technologie.',
    'hero.aiAdvanced': 'Erweiterte KI',
    'hero.fast': 'Schnell',
    'hero.secure': 'Sicher',
    'hero.createAI': 'Ihnen KI-Assistenten erstellen',

    // Dashboard
    'dashboard.welcome': 'Willkommen',
    'dashboard.quickActions': 'Schnelle Aktionen',
    'dashboard.recentActivity': 'Kürzliche Aktivität',
    'dashboard.connectedApps': 'Verbundene Apps',
    'dashboard.accountSettings': 'Kontoeinstellungen',
    'dashboard.security': 'Sicherheit',
    'dashboard.notifications': 'Benachrichtigungen',
    'dashboard.apiKeys': 'API-Schlüssel',
    'dashboard.viewProfile': 'Profil anzeigen',
    'dashboard.manageApps': 'Apps verwalten',
    'dashboard.viewActivity': 'Aktivität anzeigen',
    'dashboard.securitySettings': 'Sicherheitseinstellungen',
    'dashboard.overview': 'Übersicht',
    'dashboard.profile': 'Profil',
    'dashboard.apps': 'Anwendungen',
    'dashboard.activity': 'Aktivität',
    'dashboard.settings': 'Einstellungen',
    'dashboard.language': 'Sprache',
    'dashboard.theme': 'Design',
    'dashboard.privacy': 'Privatsphäre',
    'dashboard.twoFactor': 'Zwei-Faktor-Authentifizierung',
    'dashboard.connectedDevices': 'Verbundene Geräte',
    'dashboard.loginHistory': 'Anmeldeverlauf',
    'dashboard.dataExport': 'Datenexport',
    'dashboard.deleteAccount': 'Konto löschen',

    // Footer
    'footer.description': 'Ihr vollständiges, sichere und innovatives digitales Ökosystem.',
    'footer.products': 'Produkte',
    'footer.resources': 'Ressourcen',
    'footer.legal': 'Rechtliches',
    'footer.documentation': 'Dokumentation',
    'footer.api': 'API',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2024 LuvviX. Alle Rechte vorbehalten.',
    'footer.availableLanguages': 'Verfügbare Sprachen',

    // Forms
    'forms.title': 'LuvviX Forms',
    'forms.subtitle': 'Formulare einfach erstellen und teilen',
    'forms.description': 'Erstellen Sie interaktive Formulare und sammeln Sie Antworten in Echtzeit mit unserer intuitiven Plattform.',
    'forms.createForm': 'Formular erstellen',
    'forms.viewForms': 'Formulare anzeigen',
    'forms.myForms': 'Meine Formulare',
    'forms.responses': 'Antworten',
    'forms.analytics': 'Analysen',
    'forms.settings': 'Einstellungen',

    // News
    'news.title': 'LuvviX News',
    'news.subtitle': 'Bleiben Sie informiert',
    'news.description': 'Bleiben Sie mit personalisierten Nachrichten aus verschiedenen Quellen im Web informiert.',
    'news.categories': 'Kategorien',
    'news.trending': 'Trending',
    'news.latest': 'Neueste Nachrichten',
    'news.search': 'Nachrichten suchen...',

    // Weather
    'weather.title': 'LuvviX Wetter',
    'weather.current': 'Aktuelles Wetter',
    'weather.description': 'Überprüfen Sie das Echtzeit-Wetter für Ihren aktuellen Standort',

    // AI Studio
    'aiStudio.title': 'LuvviX AI Studio',
    'aiStudio.subtitle': 'Erstellen Sie Ihre eigenen KI-Agenten',
    'aiStudio.description': 'Revolutionäre Plattform zum Erstellen, Trainieren und Bereitstellen Ihrer eigenen KI-Agenten.',
    'aiStudio.createAgent': 'Agent erstellen',
    'aiStudio.myAgents': 'Meine Agenten',
    'aiStudio.templates': 'Vorlagen',
    'aiStudio.marketplace': 'Marktplatz',

    // Translate
    'translate.title': 'LuvviX Translate',
    'translate.subtitle': 'Echtzeit-KI-Übersetzung',
    'translate.description': 'Übersetzen Sie sofort in über 50 Sprachen mit fortschrittlicher künstlicher Intelligenz.',
    'translate.from': 'Von',
    'translate.to': 'Nach',
    'translate.translate': 'Übersetzen',
    'translate.listening': 'Zuhören...',
    'translate.speak': 'Sprechen',

    // MindMap
    'mindmap.title': 'LuvviX MindMap',
    'mindmap.subtitle': 'Intelligente KI-Mind-Maps',
    'mindmap.description': 'Erstellen Sie intelligente Mind-Maps mit KI, um Ihre Ideen zu organisieren, Kreativität zu stimulieren und Wissen zu strukturieren.',
    'mindmap.create': 'Karte erstellen',
    'mindmap.templates': 'Vorlagen',
    'mindmap.myMaps': 'Meine Karten',

    // Cloud
    'cloud.title': 'LuvviX Cloud',
    'cloud.subtitle': 'Sicherer Cloud-Speicher',
    'cloud.description': 'Speichern, synchronisieren und teilen Sie Ihre Dateien sicher mit unserer dezentralen Cloud-Lösung.',
    'cloud.upload': 'Hochladen',
    'cloud.myFiles': 'Meine Dateien',
    'cloud.shared': 'Geteilt',
    'cloud.recent': 'Kürzlich',

    // Code Studio
    'codeStudio.title': 'LuvviX Code Studio',
    'codeStudio.subtitle': 'KI-Entwicklungsstudio',
    'codeStudio.description': 'Revolutionäres Entwicklungsstudio mit intelligenter Code-Generierung und -Optimierung, angetrieben von LuvviX AI.',
    'codeStudio.generate': 'Generieren',
    'codeStudio.optimize': 'Optimieren',
    'codeStudio.analyze': 'Analysieren',

    // Authentication
    'auth.login': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.firstName': 'Vorname',
    'auth.lastName': 'Nachname',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.noAccount': 'Kein Konto?',
    'auth.hasAccount': 'Bereits ein Konto?',
    'auth.signupHere': 'Hier registrieren',
    'auth.loginHere': 'Hier anmelden',
    'auth.or': 'oder',
    'auth.googleLogin': 'Mit Google fortfahren',
    'auth.githubLogin': 'Mit GitHub fortfahren',

    // Common
    'common.loading': 'Laden...',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.view': 'Anzeigen',
    'common.share': 'Teilen',
    'common.copy': 'Kopieren',
    'common.download': 'Herunterladen',
    'common.upload': 'Hochladen',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.sort': 'Sortieren',
    'common.export': 'Exportieren',
    'common.import': 'Importieren',
    'common.refresh': 'Aktualisieren',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Vorherige',
    'common.close': 'Schließen',
    'common.open': 'Öffnen',
    'common.create': 'Erstellen',
    'common.new': 'Neu',
  },
  zh: {
    // Navigation
    'nav.home': '主页',
    'nav.ecosystem': '生态系统',
    'nav.docs': '文档',
    'nav.news': '新闻',
    'nav.support': '支持',
    'nav.login': '登录',
    'nav.signup': '注册',
    'nav.dashboard': '仪表板',
    'nav.logout': '登出',
    'nav.profile': '个人资料',
    'nav.settings': '设置',

    // Apps
    'app.aiStudio': 'AI工作室',
    'app.cloud': '云存储',
    'app.translate': '翻译',
    'app.forms': '表单',
    'app.mindmap': '思维导图',
    'app.news': '新闻',
    'app.weather': '天气',
    'app.analytics': '分析',
    'app.crawler': '爬虫',
    'app.docs': '文档生成器',
    'app.learn': '学习',
    'app.center': '中心',
    'app.codeStudio': '代码工作室',

    // Hero Section
    'hero.title': 'LuvviX ID',
    'hero.subtitle': '您的数字身份',
    'hero.description': '一个独特且安全的身份验证系统，可访问我们在喀麦隆用心打造的整个技术生态系统',
    'hero.createAccount': '创建账户',
    'hero.discoverEcosystem': '发现生态系统',
    'hero.secureAuth': '安全认证',
    'hero.instantConnection': '即时连接',
    'hero.multiplatform': '跨平台兼容',
    'hero.devApi': '开发者API',
    'hero.aiStudioNew': 'LuvviX AI工作室',
    'hero.aiStudioDesc': '几分钟内创建您自己的定制AI代理。由Cerebras技术驱动。',
    'hero.aiAdvanced': '高级AI',
    'hero.fast': '快速',
    'hero.secure': '安全',
    'hero.createAI': '创建您的AI助手',

    // Dashboard
    'dashboard.welcome': '欢迎',
    'dashboard.quickActions': '快速操作',
    'dashboard.recentActivity': '最近活动',
    'dashboard.connectedApps': '已连接应用',
    'dashboard.accountSettings': '账户设置',
    'dashboard.security': '安全',
    'dashboard.notifications': '通知',
    'dashboard.apiKeys': 'API密钥',
    'dashboard.viewProfile': '查看个人资料',
    'dashboard.manageApps': '管理应用',
    'dashboard.viewActivity': '查看活动',
    'dashboard.securitySettings': '安全设置',
    'dashboard.overview': '概览',
    'dashboard.profile': '个人资料',
    'dashboard.apps': '应用程序',
    'dashboard.activity': '活动',
    'dashboard.settings': '设置',
    'dashboard.language': '语言',
    'dashboard.theme': '主题',
    'dashboard.privacy': '隐私',
    'dashboard.twoFactor': '双因素认证',
    'dashboard.connectedDevices': '已连接设备',
    'dashboard.loginHistory': '登录历史',
    'dashboard.dataExport': '数据导出',
    'dashboard.deleteAccount': '删除账户',

    // Footer
    'footer.description': '您完整、安全且创新的数字生态系统。',
    'footer.products': '产品',
    'footer.resources': '资源',
    'footer.legal': '法律',
    'footer.documentation': '文档',
    'footer.api': 'API',
    'footer.privacy': '隐私',
    'footer.terms': '服务条款',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2024 LuvviX. 保留所有权利。',
    'footer.availableLanguages': '可用语言',

    // Forms
    'forms.title': 'LuvviX表单',
    'forms.subtitle': '轻松创建和分享表单',
    'forms.description': '使用我们直观的平台创建互动表单并实时收集响应。',
    'forms.createForm': '创建表单',
    'forms.viewForms': '查看表单',
    'forms.myForms': '我的表单',
    'forms.responses': '响应',
    'forms.analytics': '分析',
    'forms.settings': '设置',

    // News
    'news.title': 'LuvviX新闻',
    'news.subtitle': '保持信息同步',
    'news.description': '通过网络上各种来源的个性化新闻保持信息同步。',
    'news.categories': '分类',
    'news.trending': '热门',
    'news.latest': '最新新闻',
    'news.search': '搜索新闻...',

    // Weather
    'weather.title': 'LuvviX天气',
    'weather.current': '当前天气',
    'weather.description': '查看您当前位置的实时天气',

    // AI Studio
    'aiStudio.title': 'LuvviX AI工作室',
    'aiStudio.subtitle': '创建您自己的AI代理',
    'aiStudio.description': '革命性平台，用于创建、训练和部署您自己的人工智能代理。',
    'aiStudio.createAgent': '创建代理',
    'aiStudio.myAgents': '我的代理',
    'aiStudio.templates': '模板',
    'aiStudio.marketplace': '市场',

    // Translate
    'translate.title': 'LuvviX翻译',
    'translate.subtitle': '实时AI翻译',
    'translate.description': '使用先进的人工智能即时翻译50多种语言。',
    'translate.from': '从',
    'translate.to': '到',
    'translate.translate': '翻译',
    'translate.listening': '正在听...',
    'translate.speak': '说话',

    // MindMap
    'mindmap.title': 'LuvviX思维导图',
    'mindmap.subtitle': '智能AI思维导图',
    'mindmap.description': '使用AI创建智能思维导图来组织想法、激发创造力和构建知识。',
    'mindmap.create': '创建地图',
    'mindmap.templates': '模板',
    'mindmap.myMaps': '我的地图',

    // Cloud
    'cloud.title': 'LuvviX云',
    'cloud.subtitle': '安全云存储',
    'cloud.description': '使用我们的去中心化云解决方案安全地存储、同步和分享您的文件。',
    'cloud.upload': '上传',
    'cloud.myFiles': '我的文件',
    'cloud.shared': '共享',
    'cloud.recent': '最近',

    // Code Studio
    'codeStudio.title': 'LuvviX代码工作室',
    'codeStudio.subtitle': 'AI开发工作室',
    'codeStudio.description': '由LuvviX AI驱动的革命性开发工作室，具有智能代码生成和优化功能。',
    'codeStudio.generate': '生成',
    'codeStudio.optimize': '优化',
    'codeStudio.analyze': '分析',

    // Authentication
    'auth.login': '登录',
    'auth.signup': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.firstName': '名',
    'auth.lastName': '姓',
    'auth.forgotPassword': '忘记密码？',
    'auth.noAccount': '没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.signupHere': '在这里注册',
    'auth.loginHere': '在这里登录',
    'auth.or': '或',
    'auth.googleLogin': '使用Google继续',
    'auth.githubLogin': '使用GitHub继续',

    // Common
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.view': '查看',
    'common.share': '分享',
    'common.copy': '复制',
    'common.download': '下载',
    'common.upload': '上传',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.sort': '排序',
    'common.export': '导出',
    'common.import': '导入',
    'common.refresh': '刷新',
    'common.back': '返回',
    'common.next': '下一个',
    'common.previous': '上一个',
    'common.close': '关闭',
    'common.open': '打开',
    'common.create': '创建',
    'common.new': '新建',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.ecosystem': 'Экосистема',
    'nav.docs': 'Документация',
    'nav.news': 'Новости',
    'nav.support': 'Поддержка',
    'nav.login': 'Войти',
    'nav.signup': 'Регистрация',
    'nav.dashboard': 'Панель',
    'nav.logout': 'Выйти',
    'nav.profile': 'Профиль',
    'nav.settings': 'Настройки',

    // Apps
    'app.aiStudio': 'AI Студия',
    'app.cloud': 'Облако',
    'app.translate': 'Переводчик',
    'app.forms': 'Формы',
    'app.mindmap': 'Карта мыслей',
    'app.news': 'Новости',
    'app.weather': 'Погода',
    'app.analytics': 'Аналитика',
    'app.crawler': 'Краулер',
    'app.docs': 'Генератор документов',
    'app.learn': 'Обучение',
    'app.center': 'Центр',
    'app.codeStudio': 'Студия кода',

    // Hero Section
    'hero.title': 'LuvviX ID',
    'hero.subtitle': 'Ваша цифровая идентичность',
    'hero.description': 'Уникальная и безопасная система аутентификации для доступа ко всей нашей технологической экосистеме, созданной в Камеруне с любовью',
    'hero.createAccount': 'Создать аккаунт',
    'hero.discoverEcosystem': 'Открыть экосистему',
    'hero.secureAuth': 'Безопасная аутентификация',
    'hero.instantConnection': 'Мгновенное подключение',
    'hero.multiplatform': 'Кроссплатформенная совместимость',
    'hero.devApi': 'API для разработчиков',
    'hero.aiStudioNew': 'LuvviX AI Студия',
    'hero.aiStudioDesc': 'Создайте своих собственных пользовательских AI-агентов за минуты. Работает на технологии Cerebras.',
    'hero.aiAdvanced': 'Продвинутый ИИ',
    'hero.fast': 'Быстро',
    'hero.secure': 'Безопасно',
    'hero.createAI': 'Создать вашего AI-помощника',

    // Dashboard
    'dashboard.welcome': 'Добро пожаловать',
    'dashboard.quickActions': 'Быстрые действия',
    'dashboard.recentActivity': 'Недавняя активность',
    'dashboard.connectedApps': 'Подключенные приложения',
    'dashboard.accountSettings': 'Настройки аккаунта',
    'dashboard.security': 'Безопасность',
    'dashboard.notifications': 'Уведомления',
    'dashboard.apiKeys': 'API ключи',
    'dashboard.viewProfile': 'Просмотр профиля',
    'dashboard.manageApps': 'Управление приложениями',
    'dashboard.viewActivity': 'Просмотр активности',
    'dashboard.securitySettings': 'Настройки безопасности',
    'dashboard.overview': 'Обзор',
    'dashboard.profile': 'Профиль',
    'dashboard.apps': 'Приложения',
    'dashboard.activity': 'Активность',
    'dashboard.settings': 'Настройки',
    'dashboard.language': 'Язык',
    'dashboard.theme': 'Тема',
    'dashboard.privacy': 'Конфиденциальность',
    'dashboard.twoFactor': 'Двухфакторная аутентификация',
    'dashboard.connectedDevices': 'Подключенные устройства',
    'dashboard.loginHistory': 'История входов',
    'dashboard.dataExport': 'Экспорт данных',
    'dashboard.deleteAccount': 'Удалить аккаунт',

    // Footer
    'footer.description': 'Ваша полная, безопасная и инновационная цифровая экосистема.',
    'footer.products': 'Продукты',
    'footer.resources': 'Ресурсы',
    'footer.legal': 'Правовая информация',
    'footer.documentation': 'Документация',
    'footer.api': 'API',
    'footer.privacy': 'Конфиденциальность',
    'footer.terms': 'Условия использования',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2024 LuvviX. Все права защищены.',
    'footer.availableLanguages': 'Доступные языки',

    // Forms
    'forms.title': 'LuvviX Формы',
    'forms.subtitle': 'Легко создавайте и делитесь формами',
    'forms.description': 'Создавайте интерактивные формы и собирайте ответы в реальном времени с помощью нашей интуитивной платформы.',
    'forms.createForm': 'Создать форму',
    'forms.viewForms': 'Просмотр форм',
    'forms.myForms': 'Мои формы',
    'forms.responses': 'Ответы',
    'forms.analytics': 'Аналитика',
    'forms.settings': 'Настройки',

    // News
    'news.title': 'LuvviX Новости',
    'news.subtitle': 'Оставайтесь в курсе',
    'news.description': 'Оставайтесь в курсе с персонализированными новостями из различных источников в интернете.',
    'news.categories': 'Категории',
    'news.trending': 'Популярное',
    'news.latest': 'Последние новости',
    'news.search': 'Поиск новостей...',

    // Weather
    'weather.title': 'LuvviX Погода',
    'weather.current': 'Текущая погода',
    'weather.description': 'Проверьте погоду в реальном времени для вашего текущего местоположения',

    // AI Studio
    'aiStudio.title': 'LuvviX AI Студия',
    'aiStudio.subtitle': 'Создавайте своих собственных AI-агентов',
    'aiStudio.description': 'Революционная платформа для создания, обучения и развертывания ваших собственных агентов искусственного интеллекта.',
    'aiStudio.createAgent': 'Создать агента',
    'aiStudio.myAgents': 'Мои агенты',
    'aiStudio.templates': 'Шаблоны',
    'aiStudio.marketplace': 'Магазин',

    // Translate
    'translate.title': 'LuvviX Переводчик',
    'translate.subtitle': 'AI-перевод в реальном времени',
    'translate.description': 'Мгновенно переводите на более чем 50 языков с помощью продвинутого искусственного интеллекта.',
    'translate.from': 'С',
    'translate.to': 'На',
    'translate.translate': 'Перевести',
    'translate.listening': 'Слушаю...',
    'translate.speak': 'Говорить',

    // MindMap
    'mindmap.title': 'LuvviX Карта мыслей',
    'mindmap.subtitle': 'Умные AI карты мыслей',
    'mindmap.description': 'Создавайте умные карты мыслей с помощью ИИ для организации идей, стимулирования творчества и структурирования знаний.',
    'mindmap.create': 'Создать карту',
    'mindmap.templates': 'Шаблоны',
    'mindmap.myMaps': 'Мои карты',

    // Cloud
    'cloud.title': 'LuvviX Облако',
    'cloud.subtitle': 'Безопасное облачное хранилище',
    'cloud.description': 'Храните, синхронизируйте и делитесь файлами безопасно с нашим децентрализованным облачным решением.',
    'cloud.upload': 'Загрузить',
    'cloud.myFiles': 'Мои файлы',
    'cloud.shared': 'Общие',
    'cloud.recent': 'Недавние',

    // Code Studio
    'codeStudio.title': 'LuvviX Студия кода',
    'codeStudio.subtitle': 'AI студия разработки',
    'codeStudio.description': 'Революционная студия разработки с интеллектуальной генерацией и оптимизацией кода, работающая на LuvviX AI.',
    'codeStudio.generate': 'Генерировать',
    'codeStudio.optimize': 'Оптимизировать',
    'codeStudio.analyze': 'Анализировать',

    // Authentication
    'auth.login': 'Войти',
    'auth.signup': 'Регистрация',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.confirmPassword': 'Подтвердить пароль',
    'auth.firstName': 'Имя',
    'auth.lastName': 'Фамилия',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',
    'auth.signupHere': 'Зарегистрируйтесь здесь',
    'auth.loginHere': 'Войдите здесь',
    'auth.or': 'или',
    'auth.googleLogin': 'Продолжить с Google',
    'auth.githubLogin': 'Продолжить с GitHub',

    // Common
    'common.loading': 'Загрузка...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.view': 'Просмотр',
    'common.share': 'Поделиться',
    'common.copy': 'Копировать',
    'common.download': 'Скачать',
    'common.upload': 'Загрузить',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.sort': 'Сортировка',
    'common.export': 'Экспорт',
    'common.import': 'Импорт',
    'common.refresh': 'Обновить',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.previous': 'Предыдущий',
    'common.close': 'Закрыть',
    'common.open': 'Открыть',
    'common.create': 'Создать',
    'common.new': 'Новый',
  },
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.ecosystem': 'Ecosistema',
    'nav.docs': 'Documentazione',
    'nav.news': 'Notizie',
    'nav.support': 'Supporto',
    'nav.login': 'Accedi',
    'nav.signup': 'Registrati',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Esci',
    'nav.profile': 'Profilo',
    'nav.settings': 'Impostazioni',

    // Apps
    'app.aiStudio': 'AI Studio',
    'app.cloud': 'Cloud',
    'app.translate': 'Traduttore',
    'app.forms': 'Moduli',
    'app.mindmap': 'Mappa Mentale',
    'app.news': 'Notizie',
    'app.weather': 'Meteo',
    'app.analytics': 'Analytics',
    'app.crawler': 'Crawler',
    'app.docs': 'Generatore Docs',
    'app.learn': 'Impara',
    'app.center': 'Centro',
    'app.codeStudio': 'Studio Codice',

    // Hero Section
    'hero.title': 'LuvviX ID',
    'hero.subtitle': 'La tua identità digitale',
    'hero.description': 'Un sistema di autenticazione unico e sicuro per accedere a tutto il nostro ecosistema tecnologico realizzato in Camerun con amore',
    'hero.createAccount': 'Crea account',
    'hero.discoverEcosystem': 'Scopri ecosistema',
    'hero.secureAuth': 'Autenticazione sicura',
    'hero.instantConnection': 'Connessione istantanea',
    'hero.multiplatform': 'Compatibile multipiattaforma',
    'hero.devApi': 'API per sviluppatori',
    'hero.aiStudioNew': 'LuvviX AI Studio',
    'hero.aiStudioDesc': 'Crea i tuoi agenti AI personalizzati in pochi minuti. Alimentato dalla tecnologia Cerebras.',
    'hero.aiAdvanced': 'AI avanzata',
    'hero.fast': 'Veloce',
    'hero.secure': 'Sicuro',
    'hero.createAI': 'Crea il tuo assistente AI',

    // Dashboard
    'dashboard.welcome': 'Benvenuto',
    'dashboard.quickActions': 'Azioni rapide',
    'dashboard.recentActivity': 'Attività recente',
    'dashboard.connectedApps': 'App connesse',
    'dashboard.accountSettings': 'Impostazioni account',
    'dashboard.security': 'Sicurezza',
    'dashboard.notifications': 'Notifiche',
    'dashboard.apiKeys': 'Chiavi API',
    'dashboard.viewProfile': 'Visualizza profilo',
    'dashboard.manageApps': 'Gestisci app',
    'dashboard.viewActivity': 'Visualizza attività',
    'dashboard.securitySettings': 'Impostazioni sicurezza',
    'dashboard.overview': 'Panoramica',
    'dashboard.profile': 'Profilo',
    'dashboard.apps': 'Applicazioni',
    'dashboard.activity': 'Attività',
    'dashboard.settings': 'Impostazioni',
    'dashboard.language': 'Lingua',
    'dashboard.theme': 'Tema',
    'dashboard.privacy': 'Privacy',
    'dashboard.twoFactor': 'Autenticazione a due fattori',
    'dashboard.connectedDevices': 'Dispositivi connessi',
    'dashboard.loginHistory': 'Cronologia accessi',
    'dashboard.dataExport': 'Esportazione dati',
    'dashboard.deleteAccount': 'Elimina account',

    // Footer
    'footer.description': 'Il tuo ecosistema digitale completo, sicuro e innovativo.',
    'footer.products': 'Prodotti',
    'footer.resources': 'Risorse',
    'footer.legal': 'Legale',
    'footer.documentation': 'Documentazione',
    'footer.api': 'API',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Termini di servizio',
    'footer.cookies': 'Cookies',
    'footer.copyright': '© 2024 LuvviX. Tutti i diritti riservati.',
    'footer.availableLanguages': 'Lingue disponibili',

    // Forms
    'forms.title': 'LuvviX Forms',
    'forms.subtitle': 'Crea e condividi moduli facilmente',
    'forms.description': 'Crea moduli interattivi e raccogli risposte in tempo reale con la nostra piattaforma intuitiva.',
    'forms.createForm': 'Crea modulo',
    'forms.viewForms': 'Visualizza moduli',
    'forms.myForms': 'I miei moduli',
    'forms.responses': 'Risposte',
    'forms.analytics': 'Analisi',
    'forms.settings': 'Impostazioni',

    // News
    'news.title': 'LuvviX News',
    'news.subtitle': 'Rimani informato',
    'news.description': 'Rimani informato con notizie personalizzate da varie fonti sul web.',
    'news.categories': 'Categorie',
    'news.trending': 'Tendenze',
    'news.latest': 'Ultime notizie',
    'news.search': 'Cerca notizie...',

    // Weather
    'weather.title': 'LuvviX Meteo',
    'weather.current': 'Meteo attuale',
    'weather.description': 'Controlla il meteo in tempo reale per la tua posizione attuale',

    // AI Studio
    'aiStudio.title': 'LuvviX AI Studio',
    'aiStudio.subtitle': 'Crea i tuoi agenti AI',
    'aiStudio.description': 'Piattaforma rivoluzionaria per creare, addestrare e distribuire i tuoi agenti di intelligenza artificiale.',
    'aiStudio.createAgent': 'Crea agente',
    'aiStudio.myAgents': 'I miei agenti',
    'aiStudio.templates': 'Template',
    'aiStudio.marketplace': 'Marketplace',

    // Translate
    'translate.title': 'LuvviX Translate',
    'translate.subtitle': 'Traduzione AI in tempo reale',
    'translate.description': 'Traduci istantaneamente in oltre 50 lingue con intelligenza artificiale avanzata.',
    'translate.from': 'Da',
    'translate.to': 'A',
    'translate.translate': 'Traduci',
    'translate.listening': 'Ascolto...',
    'translate.speak': 'Parla',

    // MindMap
    'mindmap.title': 'LuvviX MindMap',
    'mindmap.subtitle': 'Mappe mentali AI intelligenti',
    'mindmap.description': 'Crea mappe mentali intelligenti con AI per organizzare le tue idee, stimolare la creatività e strutturare la conoscenza.',
    'mindmap.create': 'Crea mappa',
    'mindmap.templates': 'Template',
    'mindmap.myMaps': 'Le mie mappe',

    // Cloud
    'cloud.title': 'LuvviX Cloud',
    'cloud.subtitle': 'Archiviazione cloud sicura',
    'cloud.description': 'Archivia, sincronizza e condividi i tuoi file in sicurezza con la nostra soluzione cloud decentralizzata.',
    'cloud.upload': 'Carica',
    'cloud.myFiles': 'I miei file',
    'cloud.shared': 'Condiviso',
    'cloud.recent': 'Recente',

    // Code Studio
    'codeStudio.title': 'LuvviX Code Studio',
    'codeStudio.subtitle': 'Studio di sviluppo AI',
    'codeStudio.description': 'Studio di sviluppo rivoluzionario con generazione intelligente e ottimizzazione del codice alimentato da LuvviX AI.',
    'codeStudio.generate': 'Genera',
    'codeStudio.optimize': 'Ottimizza',
    'codeStudio.analyze': 'Analizza',

    // Authentication
    'auth.login': 'Accedi',
    'auth.signup': 'Registrati',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Conferma password',
    'auth.firstName': 'Nome',
    'auth.lastName': 'Cognome',
    'auth.forgotPassword': 'Password dimenticata?',
    'auth.noAccount': 'Nessun account?',
    'auth.hasAccount': 'Hai già un account?',
    'auth.signupHere': 'Registrati qui',
    'auth.loginHere': 'Accedi qui',
    'auth.or': 'o',
    'auth.googleLogin': 'Continua con Google',
    'auth.githubLogin': 'Continua con GitHub',

    // Common
    'common.loading': 'Caricamento...',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.view': 'Visualizza',
    'common.share': 'Condividi',
    'common.copy': 'Copia',
    'common.download': 'Scarica',
    'common.upload': 'Carica',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.sort': 'Ordina',
    'common.export': 'Esporta',
    'common.import': 'Importa',
    'common.refresh': 'Aggiorna',
    'common.back': 'Indietro',
    'common.next': 'Successivo',
    'common.previous': 'Precedente',
    'common.close': 'Chiudi',
    'common.open': 'Apri',
    'common.create': 'Crea',
    'common.new': 'Nuovo',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.ecosystem': 'النظام البيئي',
    'nav.docs': 'التوثيق',
    'nav.news': 'الأخبار',
    'nav.support': 'الدعم',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.dashboard': 'لوحة التحكم',
    'nav.logout': 'تسجيل الخروج',
    'nav.profile': 'الملف الشخصي',
    'nav.settings': 'الإعدادات',

    // Apps
    'app.aiStudio': 'استوديو الذكاء الاصطناعي',
    'app.cloud': 'السحابة',
    'app.translate': 'المترجم',
    'app.forms': 'النماذج',
    'app.mindmap': 'خريطة ذهنية',
    'app.news': 'الأخبار',
    'app.weather': 'الطقس',
    'app.analytics': 'التحليلات',
    'app.crawler': 'الزاحف',
    'app.docs': 'مولد المستندات',
    'app.learn': 'تعلم',
    'app.center': 'المركز',
    'app.codeStudio': 'استوديو الكود',

    // Hero Section
    'hero.title': 'LuvviX ID',
    'hero.subtitle': 'هويتك الرقمية',
    'hero.description': 'نظام مصادقة فريد وآمن للوصول إلى النظام البيئي التكنولوجي الكامل المصنوع في الكاميرون بحب',
    'hero.createAccount': 'إنشاء حساب',
    'hero.discoverEcosystem': 'اكتشف النظام البيئي',
    'hero.secureAuth': 'مصادقة آمنة',
    'hero.instantConnection': 'اتصال فوري',
    'hero.multiplatform': 'متوافق عبر المنصات',
    'hero.devApi': 'API للمطورين',
    'hero.aiStudioNew': 'LuvviX AI Studio',
    'hero.aiStudioDesc': 'أنشئ وكلاء الذكاء الاصطناعي المخصصين في دقائق. مدعوم بتقنية Cerebras.',
    'hero.aiAdvanced': 'ذكاء اصطناعي متقدم',
    'hero.fast': 'سريع',
    'hero.secure': 'آمن',
    'hero.createAI': 'أنشئ مساعدك الذكي',

    // Dashboard
    'dashboard.welcome': 'مرحباً',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.connectedApps': 'التطبيقات المتصلة',
    'dashboard.accountSettings': 'إعدادات الحساب',
    'dashboard.security': 'الأمان',
    'dashboard.notifications': 'الإشعارات',
    'dashboard.apiKeys': 'مفاتيح API',
    'dashboard.viewProfile': 'عرض الملف الشخصي',
    'dashboard.manageApps': 'إدارة التطبيقات',
    'dashboard.viewActivity': 'عرض النشاط',
    'dashboard.securitySettings': 'إعدادات الأمان',
    'dashboard.overview': 'نظرة عامة',
    'dashboard.profile': 'الملف الشخصي',
    'dashboard.apps': 'التطبيقات',
    'dashboard.activity': 'النشاط',
    'dashboard.settings': 'الإعدادات',
    'dashboard.language': 'اللغة',
    'dashboard.theme': 'السمة',
    'dashboard.privacy': 'الخصوصية',
    'dashboard.twoFactor': 'المصادقة الثنائية',
    'dashboard.connectedDevices': 'الأجهزة المتصلة',
    'dashboard.loginHistory': 'تاريخ تسجيل الدخول',
    'dashboard.dataExport': 'تصدير البيانات',
    'dashboard.deleteAccount': 'حذف الحساب',

    // Footer
    'footer.description': 'نظامك البيئي الرقمي الكامل والآمن والمبتكر.',
    'footer.products': 'المنتجات',
    'footer.resources': 'الموارد',
    'footer.legal': 'قانوني',
    'footer.documentation': 'التوثيق',
    'footer.api': 'API',
    'footer.privacy': 'الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.cookies': 'ملفات تعريف الارتباط',
    'footer.copyright': '© 2024 LuvviX. جميع الحقوق محفوظة.',
    'footer.availableLanguages': 'اللغات المتاحة',

    // Forms
    'forms.title': 'LuvviX النماذج',
    'forms.subtitle': 'أنشئ وشارك النماذج بسهولة',
    'forms.description': 'أنشئ نماذج تفاعلية واجمع الردود في الوقت الفعلي باستخدام منصتنا البديهية.',
    'forms.createForm': 'إنشاء نموذج',
    'forms.viewForms': 'عرض النماذج',
    'forms.myForms': 'نماذجي',
    'forms.responses': 'الردود',
    'forms.analytics': 'التحليلات',
    'forms.settings': 'الإعدادات',

    // News
    'news.title': 'LuvviX الأخبار',
    'news.subtitle': 'ابق على اطلاع',
    'news.description': 'ابق على اطلاع بالأخبار المخصصة من مصادر مختلفة عبر الويب.',
    'news.categories': 'الفئات',
    'news.trending': 'الرائج',
    'news.latest': 'آخر الأخبار',
    'news.search': 'البحث في الأخبار...',

    // Weather
    'weather.title': 'LuvviX الطقس',
    'weather.current': 'الطقس الحالي',
    'weather.description': 'تحقق من الطقس في الوقت الفعلي لموقعك الحالي',

    // AI Studio
    'aiStudio.title': 'LuvviX AI Studio',
    'aiStudio.subtitle': 'أنشئ وكلاء الذكاء الاصطناعي الخاصين بك',
    'aiStudio.description': 'منصة ثورية لإنشاء وتدريب ونشر وكلاء الذكاء الاصطناعي الخاصين بك.',
    'aiStudio.createAgent': 'إنشاء وكيل',
    'aiStudio.myAgents': 'وكلائي',
    'aiStudio.templates': 'القوالب',
    'aiStudio.marketplace': 'السوق',

    // Translate
    'translate.title': 'LuvviX المترجم',
    'translate.subtitle': 'ترجمة الذكاء الاصطناعي في الوقت الفعلي',
    'translate.description': 'ترجم فورياً إلى أكثر من 50 لغة باستخدام الذكاء الاصطناعي المتقدم.',
    'translate.from': 'من',
    'translate.to': 'إلى',
    'translate.translate': 'ترجم',
    'translate.listening': 'أستمع...',
    'translate.speak': 'تحدث',

    // MindMap
    'mindmap.title': 'LuvviX الخريطة الذهنية',
    'mindmap.subtitle': 'خرائط ذهنية ذكية بالذكاء الاصطناعي',
    'mindmap.description': 'أنشئ خرائط ذهنية ذكية بالذكاء الاصطناعي لتنظيم أفكارك وتحفيز الإبداع وهيكلة المعرفة.',
    'mindmap.create': 'إنشاء خريطة',
    'mindmap.templates': 'القوالب',
    'mindmap.myMaps': 'خرائطي',

    // Cloud
    'cloud.title': 'LuvviX السحابة',
    'cloud.subtitle': 'تخزين سحابي آمن',
    'cloud.description': 'خزن وزامن وشارك ملفاتك بأمان مع حلنا السحابي اللامركزي.',
    'cloud.upload': 'رفع',
    'cloud.myFiles': 'ملفاتي',
    'cloud.shared': 'مشارك',
    'cloud.recent': 'الأخيرة',

    // Code Studio
    'codeStudio.title': 'LuvviX استوديو الكود',
    'codeStudio.subtitle': 'استوديو تطوير الذكاء الاصطناعي',
    'codeStudio.description': 'استوديو تطوير ثوري مع توليد وتحسين الكود الذكي مدعوم بـ LuvviX AI.',
    'codeStudio.generate': 'توليد',
    'codeStudio.optimize': 'تحسين',
    'codeStudio.analyze': 'تحليل',

    // Authentication
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.firstName': 'الاسم الأول',
    'auth.lastName': 'اسم العائلة',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'auth.signupHere': 'سجل هنا',
    'auth.loginHere': 'سجل الدخول هنا',
    'auth.or': 'أو',
    'auth.googleLogin': 'المتابعة مع Google',
    'auth.githubLogin': 'المتابعة مع GitHub',

    // Common
    'common.loading': 'جارٍ التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تحرير',
    'common.view': 'عرض',
    'common.share': 'مشاركة',
    'common.copy': 'نسخ',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.refresh': 'تحديث',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.close': 'إغلاق',
    'common.open': 'فتح',
    'common.create': 'إنشاء',
    'common.new': 'جديد',
  },
};

const detectBrowserLanguage = (): string => {
  const browserLang = navigator.language.toLowerCase();
  
  if (browserLang.startsWith('fr')) return 'fr';
  if (browserLang.startsWith('en')) return 'en';
  if (browserLang.startsWith('es')) return 'es';
  if (browserLang.startsWith('pt')) return 'pt';
  if (browserLang.startsWith('de')) return 'de';
  if (browserLang.startsWith('zh')) return 'zh';
  if (browserLang.startsWith('ru')) return 'ru';
  if (browserLang.startsWith('it')) return 'it';
  if (browserLang.startsWith('ar')) return 'ar';
  
  return 'fr'; // Default to French
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<string>(() => {
    const saved = localStorage.getItem('luvvix-language') as string;
    return saved || detectBrowserLanguage();
  });

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    localStorage.setItem('luvvix-language', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  const t = (key: string): string => {
    const translation = translations[language][key];
    if (!translation) return key;
    return translation;
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
