workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "io.codemagic.sample.reactnative"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Install npm dependencies
        script: |
          npm install

      - name: Run Expo Prebuild
        script: |
          npx expo prebuild

      - name: Set up app/build.gradle
        script: |
          mv ./support-files/build.gradle android/app

      - name: Build Android release (unsigned)
        script: |
          # Se déplacer dans le répertoire android pour le build
          cd android
          # Utiliser assembleRelease pour créer un APK non signé (en évitant le keystore)
          ./gradlew assembleRelease
          
    artifacts:
      - android/app/build/outputs/**/*.apk   # Définir l'APK comme artefact

    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
